export const initialSettings = {
  brandName: 'CCT 算链集团',
  heroTitle: '让智能，\n成为生产力。',
  heroTitleEn: 'Intelligence.\nInto impact.',
  heroSubtitle: 'CCT AI 产业计算网络，从推理基础设施、企业智能体到行业系统与可信治理，构建可评测、可审计、可计量的生产级路径。',
  heroSubtitleEn: 'CCT AI Industrial Network connects inference infrastructure, enterprise agents, industry systems and trusted governance into a measurable path to production.',
  contactEmail: 'contact@cct.example',
};

// These are editable capability descriptions, not customer references or claims of completed delivery.
export const initialContent = [
  {
    type: 'service', slug: 'ai-transformation', category: 'AI TRANSFORMATION', featured: true,
    title: '企业 AI 转型', titleEn: 'Enterprise AI transformation',
    summary: '让 AI 进入真实业务流程，以明确的基线、责任与验收标准推进组织升级。',
    summaryEn: 'Bring AI into operational workflows with clear baselines, ownership and acceptance criteria.',
    body: '从业务问题开始，而不是从采购工具开始。梳理高频流程、数据可用性与组织责任，选择能够测量价值的首批场景。\n\n交付路径包括：现状诊断与流程地图、场景优先级与收益假设、受控试点、评估与人工复核、分阶段推广。每个阶段明确业务负责人、输入数据、验收证据和停止条件。\n\n适用场景：企业知识检索、客户服务辅助、经营分析、内容生产与运营协同。涉及人事、财务审批或其他重大决定时，保留明确的人工决策与审计机制。具体能力、范围与服务水平在项目评估后确认。',
    bodyEn: 'Begin with a business problem, not a tool purchase. Map frequent workflows, data readiness and decision ownership before selecting measurable pilot use cases.\n\nThe proposed delivery path includes discovery, a workflow map, prioritized opportunities, a controlled pilot, human-reviewed evaluation and phased rollout. Each stage defines accountable owners, data inputs, acceptance evidence and stop conditions.\n\nPotential applications include enterprise knowledge retrieval, service assistance, operational analysis and content operations. Consequential HR, financial or other decisions retain human accountability and audit controls. Scope and service levels are confirmed through project assessment.',
  },
  {
    type: 'service', slug: 'agent-systems', category: 'AGENT SYSTEMS', featured: true,
    title: '智能体与工作流', titleEn: 'Agents & intelligent workflows',
    summary: '把模型能力转化为可编排的任务执行，让每一次调用都有权限、记录与边界。',
    summaryEn: 'Turn model capabilities into orchestrated work with explicit permissions, traceability and boundaries.',
    body: '面向业务任务设计智能体：明确目标、可调用工具、数据权限和人机交接点。知识检索、结构化生成与业务系统连接在同一流程中完成，避免孤立的对话窗口。\n\n规划能力包括工具白名单、审批节点、运行追踪、重试与超时、费用限额、离线评测、失败回退和版本管理。外部写入、交易与高影响操作默认设置人工确认。\n\n从单个流程的受控试点逐步扩展。以任务完成率、准确性、人工介入率、端到端耗时与单位成本评估系统，而不以演示效果代替业务结果。',
    bodyEn: 'Design agents around a business task: define the objective, available tools, data permissions and human handoff points. Combine retrieval, structured generation and business-system integration within a coherent workflow.\n\nPlanned controls include tool allowlists, approval steps, run traces, retries and timeouts, spending limits, offline evaluation, fallbacks and versioning. External writes, transactions and consequential actions require human approval by default.\n\nExpand from one controlled workflow. Evaluate completion, correctness, intervention rate, end-to-end time and unit cost rather than relying on a compelling demonstration.',
  },
  {
    type: 'service', slug: 'compute-infrastructure', category: 'COMPUTE INFRASTRUCTURE', featured: true,
    title: '算力与基础设施', titleEn: 'Compute & infrastructure',
    summary: '围绕负载、成本与数据边界，设计从开发验证到生产运行的算力架构。',
    summaryEn: 'Design compute architecture around workload requirements, cost and data boundaries.',
    body: '根据模型规模、吞吐、延迟、部署区域与数据敏感度评估算力需求，比较公有云、私有化与混合部署的适用条件。\n\n架构规划覆盖模型服务、任务调度、资源配额、监控告警、容量评估、备份恢复与成本归集。算力资源的实际供应、价格、可用区和服务水平以具体供应商及合同为准。\n\n先用代表性负载建立性能与成本基线，再决定优化和扩容。对外展示的任何运行指标应来自经过验证的真实监控；网站不以模拟节点数或演示动画宣称基础设施规模。',
    bodyEn: 'Assess compute needs using model size, throughput, latency, deployment region and data sensitivity. Compare public cloud, private and hybrid deployment against concrete requirements.\n\nArchitecture planning covers model serving, scheduling, resource quotas, monitoring, capacity, recovery and cost allocation. Actual supply, pricing, regions and service levels depend on the selected provider and contract.\n\nEstablish performance and cost baselines using representative workloads before optimization or expansion. Public operating metrics must come from verified monitoring; visual demonstrations do not represent infrastructure scale.',
  },
  {
    type: 'service', slug: 'trusted-data', category: 'TRUSTED DATA', featured: true,
    title: '可信数据与协作', titleEn: 'Trusted data & collaboration',
    summary: '把数据治理、可追溯机制与适用的分布式技术连接起来，建立协作基础。',
    summaryEn: 'Connect data governance, traceability and fit-for-purpose distributed technology.',
    body: '先确认数据权属、授权与质量，再讨论跨组织协作的技术路径。通过数据目录、分级分类、访问控制和生命周期管理建立可用的数据基础。\n\n对确有多方协作与存证需求的场景，评估签名、可信时间戳、审计日志或分布式账本的适用性。技术选择服从业务必要性，不将上链等同于数据真实或合规。\n\n涉及设备网络、DePIN 或其他分布式资源协同时，先验证设备身份、计量可信度、资源质量与运维机制；经济机制与商业模式需独立评估。',
    bodyEn: 'Establish data ownership, authorization and quality before selecting a cross-organization collaboration architecture. Build a usable foundation with cataloging, classification, access controls and lifecycle management.\n\nWhere multiparty collaboration and evidence are necessary, assess signatures, trusted timestamps, audit logs or distributed ledgers. Technology follows business necessity; recording data on a ledger does not prove its accuracy or compliance.\n\nFor device networks, DePIN or distributed resources, validate identity, metering, quality and operations first. Economic mechanisms and business models require separate assessment.',
  },
  {
    type: 'solution', slug: 'enterprise-knowledge', category: 'ENTERPRISE', featured: true,
    title: '企业知识与经营协同', titleEn: 'Enterprise knowledge & operations',
    summary: '连接分散的知识与流程，为员工提供有依据、可追溯的业务辅助。',
    summaryEn: 'Connect fragmented knowledge and workflows to deliver evidence-based operational assistance.',
    body: '典型问题：资料分散、检索困难、口径不一致，以及重复汇总造成的协作成本。\n\n方案方向：建立授权文档索引，保留来源引用与版本信息；按照岗位权限检索知识；结合结构化模板辅助制作报告、任务清单与经营摘要。\n\n试点验证：选取一个部门和明确的知识范围，记录检索成功率、引用准确率、回答拒绝率、处理时长与用户反馈。敏感资料遵循权限继承与最小访问原则。此页面为方案描述，实际系统范围需经需求评估。',
    bodyEn: 'Typical challenges include fragmented documentation, difficult retrieval, inconsistent answers and repetitive reporting.\n\nThe proposed approach indexes authorized documents with source references and version context, applies role-based access and supports reports, task lists and operating summaries through structured templates.\n\nA pilot starts with one department and a defined corpus. Evaluation measures retrieval success, citation accuracy, refusal behavior, handling time and feedback. Sensitive documents retain inherited permissions and least-privilege access. This is a solution description; implementation scope requires assessment.',
  },
  {
    type: 'solution', slug: 'education-intelligence', category: 'EDUCATION', featured: true,
    title: '教育与人才发展', titleEn: 'Education & workforce development',
    summary: '支持教学准备、知识服务与运营协同，让教师与管理者掌握最终判断。',
    summaryEn: 'Support teaching preparation, knowledge services and operations while preserving human judgment.',
    body: '围绕教学准备、课程资料检索、行政流程与人才培养支持设计可控的 AI 辅助工作流。\n\n实施边界：学生信息、未成年人数据和教学资料按敏感程度分级处理；教学评价、成绩、资格认定及人事决定保留人工决策。模型输出应由具备相应责任的人员复核。\n\n分阶段验证：先测量现有流程成本与质量，再开展小范围试点，对比节省的工时、质量变化与新增复核成本。外部案例仅作为试点假设，不直接转换为裁员承诺或保证收益。',
    bodyEn: 'Design controlled AI assistance for lesson preparation, curriculum retrieval, administrative workflows and workforce development.\n\nBoundaries: classify student information, minors’ data and teaching materials by sensitivity. Teaching evaluation, grades, certification and employment decisions retain human authority. Accountable staff review generated outputs.\n\nMeasure existing cost and quality before a small pilot. Compare time saved, changes in quality and the additional cost of review. External evidence informs hypotheses; it does not establish guaranteed returns or staffing outcomes.',
  },
  {
    type: 'solution', slug: 'industrial-intelligence', category: 'INDUSTRY', featured: true,
    title: '产业智能与设备协同', titleEn: 'Industrial intelligence',
    summary: '把现场知识、设备数据与业务系统结合，探索可落地的产业 AI 场景。',
    summaryEn: 'Connect operational knowledge, equipment data and business systems for practical industrial AI.',
    body: '以现场问题为入口，评估设备知识检索、维护辅助、质量记录分析与生产运营协同的实际价值。\n\n先检查数据质量、设备接口、网络条件和安全要求，再决定边缘或云端部署。系统接入采用权限隔离，生产控制指令与安全相关操作保留既有控制和审批机制。\n\n试点使用可复核的样本集和明确的验收标准，记录误报、漏报、响应时间与人员反馈。数字化建议需要由现场专业人员验证，不能直接取代设备安全规程。',
    bodyEn: 'Start from an operational problem and assess the value of equipment knowledge retrieval, maintenance assistance, quality-record analysis and workflow coordination.\n\nEvaluate data quality, interfaces, connectivity and safety requirements before choosing edge or cloud deployment. Isolate integration permissions; production-control commands and safety-related actions preserve existing controls and approvals.\n\nUse reviewable samples and explicit acceptance criteria. Track false positives, missed findings, response time and staff feedback. On-site specialists validate recommendations; generated advice does not replace equipment safety procedures.',
  },
  {
    type: 'solution', slug: 'low-altitude-ecosystem', category: 'EMERGING ECOSYSTEMS', featured: true,
    title: '低空经济与分布式网络', titleEn: 'Low-altitude & distributed networks',
    summary: '探索任务协同、数据管理与资源调度，为新兴产业建立可验证的技术路径。',
    summaryEn: 'Explore mission coordination, data management and resource scheduling for emerging industries.',
    body: '面向低空经济与分布式设备协作，探索任务资料管理、设备状态汇聚、运营数据分析和资源调度辅助等技术方向。\n\n项目启动前需明确应用场景、设备能力、必要授权、责任主体与适用的运营规则。网站展示技术方向，不表示已取得飞行、运营或其他特定资质。\n\n先在受控环境验证数据链路、身份认证、故障回退与人员协同。涉及实际设备操作、飞行决策与现场安全时，专业运营人员与既有安全流程保持最终控制。',
    bodyEn: 'Explore mission-document management, device-status aggregation, operational analytics and resource-scheduling assistance for low-altitude and distributed device ecosystems.\n\nDefine the use case, device capabilities, required authorizations, accountable operators and applicable operating rules before a project begins. This page presents technology directions and does not claim flight, operating or other specific qualifications.\n\nValidate data paths, identity, fallback and human coordination in a controlled environment. Qualified operators and established safety processes retain final control of physical operations, flight decisions and field safety.',
  },
  {
    type: 'insight', slug: 'from-ai-demo-to-delivery', category: 'PERSPECTIVES', featured: true,
    title: '从 AI 演示到业务交付，中间还缺什么？', titleEn: 'What turns an AI demo into business delivery?',
    summary: '一条可验证的交付路径，需要同时回答价值、数据、质量、责任与运行五个问题。',
    summaryEn: 'A verifiable delivery path must address value, data, quality, accountability and operations.',
    body: '演示让人看见可能性，交付需要证明可用性。进入真实业务后，系统要面对不完整输入、变化的权限、多样的用户和不可预期的失败。\n\n第一步是建立业务基线：当前耗时、质量、成本与风险分别是多少？第二步是确定评估集与验收标准，覆盖常见任务、边界情况和必须拒绝的请求。第三步是设计人工接管、运行监控与问题回溯。\n\n只有将这些条件与业务目标一起写入交付范围，团队才可能判断系统是否值得扩大应用。这是一篇方法论观点文章，具体结论需要项目实测支持。',
    bodyEn: 'A demo shows possibility; delivery requires evidence of usability. Real workflows introduce incomplete inputs, changing permissions, diverse users and unexpected failures.\n\nFirst establish the operating baseline: current time, quality, cost and risk. Then define evaluation samples and acceptance criteria across normal tasks, edge cases and requests the system must refuse. Finally design human takeover, monitoring and incident traceability.\n\nPutting these conditions alongside business goals makes an expansion decision possible. This article presents a methodology; project-specific conclusions require measurement.',
  },
  {
    type: 'insight', slug: 'compute-that-fits-the-workload', category: 'ENGINEERING', featured: false,
    title: '算力规划，先回答负载问题', titleEn: 'Compute planning begins with the workload',
    summary: '从吞吐、延迟、可用性和数据边界出发，建立可比较的性能与成本基线。',
    summaryEn: 'Build comparable performance and cost baselines around throughput, latency, availability and data boundaries.',
    body: '算力选型不是孤立比较设备参数。模型、上下文长度、并发、量化策略与缓存方式都会改变资源需求。\n\n规划时应选择代表性任务，记录端到端响应时间、有效吞吐、失败率和单位任务成本。再结合部署区域、数据边界、恢复目标与供应条件比较方案。\n\n公开的基准测试可以帮助提出问题，但不能代替自身工作负载测试。容量与成本承诺应建立在双方确认的负载、测量方法和服务水平之上。',
    bodyEn: 'Compute selection is not a standalone comparison of hardware specifications. Models, context length, concurrency, quantization and caching all change resource demand.\n\nUse representative tasks to measure end-to-end latency, useful throughput, failure rate and cost per completed task. Compare options against deployment regions, data boundaries, recovery objectives and resource availability.\n\nPublic benchmarks inform questions but do not replace workload-specific testing. Capacity and cost commitments require agreed workloads, measurement methods and service levels.',
  },
  {
    type: 'insight', slug: 'governance-by-design', category: 'RESPONSIBLE AI', featured: false,
    title: '把治理放进系统设计的第一天', titleEn: 'Build governance into day one',
    summary: '从权限、来源引用、人工复核和审计记录入手，让可信成为具体的系统能力。',
    summaryEn: 'Make trust concrete through permissions, source attribution, human review and auditable records.',
    body: '治理不应是上线后的补充文档。它决定系统能读取哪些资料、调用哪些工具、执行哪些动作，以及出现问题时谁能解释和处理。\n\n在设计阶段确定数据分级、访问控制、保留期限、模型使用范围与人工审批点。对重要输出保留来源与版本，对关键操作记录主体、时间和动作，避免在日志中复制敏感内容。\n\n治理也需要验证：测试越权访问、错误引用、工具误调用和失败回退。明确知道系统何时需要停止与转交给人，是可靠交付的一部分。',
    bodyEn: 'Governance is not an after-launch document. It determines which information a system can access, which tools it can call, which actions it may take and who can explain or resolve failures.\n\nDefine data classification, access, retention, permitted model use and human approval points during design. Preserve source and version context for important outputs, and log actors, timestamps and key actions without unnecessarily duplicating sensitive content.\n\nGovernance also needs testing: unauthorized access, incorrect references, tool misuse and failure recovery. Knowing when to stop and hand control to a person is part of reliable delivery.',
  },
  {
    type: 'service', slug: 'inference-fabric', category: 'CCT INFERENCE FABRIC', featured: true,
    title: '推理基础设施与 FinOps', titleEn: 'Inference fabric & FinOps',
    summary: '统一接入异构算力与多模型，把吞吐、时延、质量、成本和服务等级放进同一套运行控制面。',
    summaryEn: 'Unify heterogeneous compute and models across throughput, latency, quality, cost and service-level controls.',
    body: 'CCT Inference Fabric 面向进入生产阶段的 AI 工作负载，规划统一推理网关、模型路由、批处理、缓存、量化、弹性调度、容量与故障隔离。它关注的是每个已完成任务的成本和质量，而不是孤立的 GPU 参数。\n\n运行控制覆盖租户与配额、调用追踪、SLA、预算钱包、成本归集、容量预测、降级与灾备。先用代表性负载建立基线，再选择公有云、私有化或混合架构。\n\n页面描述的是产品化能力方向。支持的芯片、云区域、峰值并发、可用性与价格，须在技术验收和资源合同中逐项确认。',
    bodyEn: 'CCT Inference Fabric is designed for production AI workloads, with a unified inference gateway, model routing, batching, caching, quantization, elastic scheduling, capacity controls and fault isolation. It optimizes the cost and quality of a completed task rather than comparing GPU specifications in isolation.\n\nThe operating plane covers tenants and quotas, traces, service levels, budget wallets, cost allocation, capacity forecasts, degradation and recovery. Representative workloads establish a baseline before selecting public, private or hybrid infrastructure.\n\nThis page describes a product direction. Supported accelerators, regions, peak concurrency, availability and pricing require technical acceptance and a resource contract.',
  },
  {
    type: 'service', slug: 'private-ai', category: 'CCT PRIVATE AI', featured: true,
    title: '私有 AI 与数据主权', titleEn: 'Private AI & data sovereignty',
    summary: '以数据、知识产权和部署控制为边界，设计本地、VPC、单租户与离线环境的 AI 系统。',
    summaryEn: 'Design on-premises, VPC, single-tenant and offline AI around data, IP and deployment control.',
    body: '从数据驻留、网络隔离、模型选择、密钥管理和运维责任出发，形成单租户、专有云、本地机房或受控离线环境的部署方案。\n\n能力清单包括细粒度权限、敏感数据脱敏、密钥托管、模型与数据不出域策略、异构硬件适配、审计证据、备份恢复和多云迁移。每项能力通过架构评审、渗透测试或恢复演练形成验收证据。\n\n“主权”不代表天然合规。具体数据处理活动仍需由客户的法务、安全和数据责任人确认适用要求。',
    bodyEn: 'Start from residency, network isolation, model choice, key management and operating accountability to design single-tenant, private-cloud, on-premises or controlled offline deployment.\n\nThe capability checklist covers granular access, sensitive-data handling, customer-managed keys, in-domain model and data policies, heterogeneous hardware, audit evidence, recovery and multi-cloud portability. Architecture reviews, security tests and recovery exercises provide acceptance evidence.\n\nSovereign deployment is not automatically compliant. The customer’s legal, security and data owners must confirm requirements for each processing activity.',
  },
  {
    type: 'service', slug: 'ai-control-plane', category: 'CCT AI CONTROL PLANE', featured: true,
    title: '智能体治理控制平面', titleEn: 'AI & agent control plane',
    summary: '登记每个模型、智能体、工具和责任人，在上线前评测，在运行中追踪，在高影响动作前保留人工审批。',
    summaryEn: 'Register every model, agent, tool and owner; evaluate before release, trace in production and gate consequential actions.',
    body: '控制平面建立模型与智能体登记册，记录版本、用途、数据范围、工具权限、责任人和风险等级。策略即代码把允许、拒绝、审批、预算与停机条件写入运行链路。\n\n上线门禁覆盖离线评测、红队测试、提示注入与数据泄漏测试、来源引用、拒绝行为和回归检查；运行阶段保留追踪、内容标识、事件响应与审计证据包。\n\n治理框架可参考 NIST AI RMF 等公开标准，但是否符合特定法律、行业规范或认证要求，需要独立的法务与认证评估。',
    bodyEn: 'The control plane maintains a registry of models and agents, recording version, purpose, data scope, tool permissions, accountable owner and risk tier. Policy as code brings allow, deny, approval, budget and shutdown rules into the runtime.\n\nRelease gates cover offline evaluation, red teaming, prompt-injection and data-loss tests, citation behavior, refusal and regression. Production controls add traces, content disclosure, incident response and audit evidence.\n\nPublic frameworks such as the NIST AI RMF can inform design. Compliance with a specific law, sector rule or certification requires independent legal and assurance review.',
  },
  {
    type: 'service', slug: 'green-compute', category: 'CCT GREEN COMPUTE', featured: false,
    title: '算能协同与容量治理', titleEn: 'Compute-energy coordination',
    summary: '把 GPU 利用率、队列、功耗、热风险、供电与成本联动，提前发现限制生产交付的容量瓶颈。',
    summaryEn: 'Connect utilization, queues, power, thermal risk, supply and cost to expose delivery bottlenecks early.',
    body: '算能协同关注工作负载与物理资源之间的真实约束。统一观察 GPU 利用率、排队时间、单位任务能耗、机架功率、热风险、容量余量与电力来源台账。\n\n运营策略可包括峰谷调度、冷热数据分层、容量预测、故障与热风险预警，以及成本、能耗和时延的多目标优化。PUE、碳排和可再生能源比例只有在测量边界、时间范围与凭证完整时才对外披露。\n\n实际节能与成本效果以现场基线、设备条件和试运行数据为准。',
    bodyEn: 'Compute-energy coordination addresses physical constraints behind AI workloads. It observes GPU utilization, queue time, energy per task, rack power, thermal risk, remaining capacity and electricity-source records in one operating view.\n\nOperating strategies may include time-shifting, storage tiering, capacity forecasts, failure and thermal alerts, and multi-objective optimization across cost, energy and latency. PUE, carbon and renewable claims require defined boundaries, time periods and evidence.\n\nSavings and cost outcomes depend on the measured site baseline, equipment and pilot results.',
  },
  {
    type: 'service', slug: 'physical-ai-lab', category: 'CCT PHYSICAL AI LAB', featured: false, claimScope: 'proposal',
    title: '具身智能联合实验室', titleEn: 'Physical AI joint lab',
    summary: '以数字孪生、工业视觉、边缘推理和安全围栏开展联合试点，通过阶段门决定是否进入现场规模化。',
    summaryEn: 'Run gated pilots in digital twins, industrial vision, edge inference and safety controls before field scale-up.',
    body: '具身智能目前适合以联合验证方式推进。先在仿真或数字孪生环境定义任务、失败边界与安全约束，再进入受控现场测试。\n\n试点模块包括传感器与视觉、边缘推理、任务规划、机器人接口、人工接管、操作日志和故障回退。验收关注任务成功率、安全事件、人工介入、节拍、维护成本与停机影响。\n\n合作前需明确设备责任方、现场资质、安全方案和验收标准，再决定是否进入规模化部署。',
    bodyEn: 'Physical AI is advanced through joint validation. Define tasks, failure boundaries and safety constraints in simulation or a digital twin before controlled field testing.\n\nPilot modules cover sensors and vision, edge inference, planning, robot interfaces, human takeover, operating logs and fail-safe behavior. Acceptance measures task success, safety events, intervention, cycle time, maintenance cost and downtime impact.\n\nBefore scaling, confirm equipment ownership, field qualifications, safety plans and acceptance criteria.',
  },
  {
    type: 'solution', slug: 'customer-operations-agents', category: 'CUSTOMER OPERATIONS', featured: true,
    title: '客户运营智能体', titleEn: 'Customer operations agents',
    summary: '把多渠道消息、知识、线索、工单与 CRM 回写串成可追踪的执行闭环。',
    summaryEn: 'Connect conversations, knowledge, leads, tickets and CRM updates into a traceable execution loop.',
    body: '输入包括授权渠道消息、客户上下文、产品知识和服务规则。智能体识别意图，检索依据，生成或执行下一步，并在外部写入、承诺、退款和敏感场景前触发人工审批。\n\n执行证据包含所用来源、工具调用、审批人、状态回写与最终结果。异常、超时和低置信度任务进入人工队列，避免静默失败。\n\n试点 KPI 包括一次解决率、准确率、人工复核率、响应时间、转人工原因、单位处理成本与客户反馈。基线和目标由项目双方共同确认。',
    bodyEn: 'Inputs include authorized conversations, customer context, product knowledge and service rules. Agents classify intent, retrieve evidence, prepare or execute the next step, and request human approval before external writes, commitments, refunds or sensitive actions.\n\nExecution evidence records sources, tool calls, approvals, status updates and outcomes. Exceptions, timeouts and low-confidence tasks enter a human queue rather than failing silently.\n\nPilot metrics include first-contact resolution, correctness, review rate, response time, handoff reasons, unit cost and customer feedback. The project parties agree the baseline and targets.',
  },
  {
    type: 'solution', slug: 'geo-growth-intelligence', category: 'GEO & GROWTH', featured: true,
    title: 'GEO 增长智能系统', titleEn: 'GEO growth intelligence',
    summary: '持续测量品牌在生成式搜索中的可见度、引用与竞品差距，把诊断、内容执行和复测连成闭环。',
    summaryEn: 'Measure visibility, citations and competitive gaps in generative search, then connect diagnosis, action and remeasurement.',
    body: '系统按预先定义的问题集和目标受众运行测量，记录不同模型或入口的品牌出现、来源引用、答案位置和竞品表现。诊断将问题映射到内容缺口、权威信源、技术可抓取性与品牌实体一致性。\n\n执行工作台形成选题、证据、审核、发布准备与复测任务。所有内容保留来源和人工编辑，避免以批量生成替代真实专业知识。\n\n结果以可重复的问题集、时间窗和来源证据呈现。生成式答案会随模型、地区与时间变化，因此不承诺固定排名或永久引用。',
    bodyEn: 'The system runs a defined question set for target audiences and records brand presence, citations, answer position and competitor performance across models or surfaces. Diagnosis maps gaps to content, authoritative sources, crawlability and brand-entity consistency.\n\nThe workbench creates topics, evidence, review, publication-ready work and remeasurement tasks. Sources and human editing stay attached to content so volume does not replace expertise.\n\nResults use repeatable questions, time windows and source evidence. Generative answers vary by model, region and time; fixed rankings or permanent citations are not promised.',
  },
  {
    type: 'solution', slug: 'ai-commerce-operations', category: 'AI COMMERCE', featured: false,
    title: 'AI 电商与内容运营', titleEn: 'AI commerce & content operations',
    summary: '连接商品知识、内容生产、营销协同、客服与订单，让每次自动化都有审核、预算和结果证据。',
    summaryEn: 'Connect product knowledge, content, campaigns, service and orders with review, budget and outcome evidence.',
    body: '以商品主数据和品牌规则为基础，编排研究、文案、素材、渠道适配、客服辅助与订单协同。不同模型按任务质量、成本和时延路由，生成内容在发布前经过版权、事实、品牌与合规审核。\n\n涉及价格、库存、订单、退款和用户权益的动作，通过业务系统 API 和权限策略执行；关键变更保留人工批准与回滚路径。\n\n试点衡量内容一次通过率、制作周期、人工返工、转化链路、服务质量与单位成本。任何增长比例都需来自明确的对照基线。',
    bodyEn: 'Use governed product data and brand rules to orchestrate research, copy, media, channel adaptation, service assistance and order coordination. Route models by quality, cost and latency, and review copyright, facts, brand and compliance before publishing.\n\nPrice, inventory, order, refund and customer-rights actions use governed business APIs. Consequential changes retain human approval and rollback.\n\nPilots measure first-pass acceptance, production cycle, rework, conversion flow, service quality and unit cost. Any growth percentage requires a defined comparison baseline.',
  },
  {
    type: 'solution', slug: 'ai-public-services', category: 'AI PUBLIC SERVICES', featured: false, claimScope: 'proposal',
    title: 'AI 公共服务解决方案', titleEn: 'AI public service solution',
    summary: '让政策咨询、办事导引、材料预审与公共资源服务更便捷，同时保留权威来源、人工审核和全程记录。',
    summaryEn: 'Improve policy enquiries, service guidance, document pre-checks and public resources with authoritative sources, human review and complete records.',
    body: '从高频、规则相对清晰的公共服务事项开始，建立权威政策库、办事指南、表单规则和人工转接机制。系统可以辅助回答、政策匹配、材料清单核对、智能派单和进度提醒。\n\n交付建议采用“场景建设 + 年度运营 + 按使用量结算”的组合方式，并把知识更新、响应时效、引用准确率、转人工率和用户满意度写入验收。\n\n涉及行政审批、医疗、教育、社保、执法等高影响事项时，AI 只提供辅助。最终决定、内容发布和例外处理由有权人员完成；涉密信息不得进入非涉密模型。',
    bodyEn: 'Begin with high-volume services governed by clear rules. Build an authoritative policy corpus, service guides, form rules and human handoffs. The system can assist answers, policy matching, checklist review, routing and reminders.\n\nA practical commercial structure combines implementation, managed operations and usage-based fees, with acceptance measures for knowledge freshness, response time, citation accuracy, handoff and user satisfaction.\n\nAI remains assistive for approvals, health, education, social benefits, enforcement and other consequential services. Authorized people make decisions, publish content and handle exceptions. Classified information must not enter non-classified models.',
  },
  {
    type: 'solution', slug: 'ai-series-studio', category: 'AI ENTERTAINMENT', featured: false, claimScope: 'proposal',
    title: 'AI 漫剧与短剧工作室', titleEn: 'AI comics & short-drama studio',
    summary: '把选题、剧本、分镜、角色、画面、配音、多语言版本与渠道发行组织成可复用的内容生产线。',
    summaryEn: 'Organize concepts, scripts, storyboards, characters, visuals, dubbing, localization and distribution into a reusable production line.',
    body: '适用于国内漫剧、短剧、品牌故事和海外短视频。制作链路包括选题评估、剧本拆解、分镜、角色资产、图像与视频生成、配音字幕、质量检查、多语言本地化和渠道版本管理。\n\n商业模式可以组合制作服务、内容分成、IP 授权和海外发行。建议先制作 3 集样片及中英文版本，测量单集成本、制作周期、完播率、付费转化和平台审核通过率，再决定扩量。\n\n项目必须建立角色和素材授权台账，核对人物肖像、音乐、字体、训练来源和品牌资产。平台发布、广告标识和未成年人相关内容需要人工审核。',
    bodyEn: 'Suitable for domestic comics, short drama, brand stories and international short video. The workflow covers concept testing, script breakdown, storyboards, character assets, image and video generation, dubbing, subtitles, quality review, localization and channel versions.\n\nCommercial models can combine production fees, revenue sharing, IP licensing and international distribution. Begin with three pilot episodes and Chinese and English versions, measuring unit cost, cycle time, completion, paid conversion and approval rate before scaling.\n\nMaintain rights records for characters, media, likeness, music, fonts, training sources and brand assets. Platform release, advertising disclosure and content involving minors require human review.',
  },
  {
    type: 'solution', slug: 'ai-foreign-trade', category: 'AI GLOBAL TRADE', featured: false, claimScope: 'proposal',
    title: 'AI 外贸增长系统', titleEn: 'AI foreign-trade growth system',
    summary: '连接市场研究、买家发现、多语言询盘、报价准备、跟进任务与 CRM，帮助外贸团队把信息变成商机。',
    summaryEn: 'Connect market research, buyer discovery, multilingual enquiries, quotation preparation, follow-up and CRM to turn information into opportunities.',
    body: '围绕一个国家、一条产品线和明确的目标客户建立外贸知识库。系统辅助研究市场规模、买家画像、竞争产品和渠道，基于已审核产品资料生成多语言介绍、询盘回复和跟进建议。\n\n销售人员保留客户筛选、报价、交期、支付条款和合同承诺的最终决定。系统记录资料来源、翻译版本、跟进状态和 CRM 回写，便于团队复盘。\n\n试点测量有效线索率、回复时间、销售跟进时间、报价转化和获客成本。出口管制、制裁、海关、税务、产品认证和当地法律由专业人员审查。',
    bodyEn: 'Build a trade knowledge base around one country, product line and target buyer. The system assists market sizing, buyer profiles, competitive research and channels, then prepares multilingual product material, enquiry responses and follow-up based on approved data.\n\nSalespeople retain final authority over qualification, quotation, lead time, payment terms and contracts. Sources, translations, follow-up status and CRM updates remain traceable.\n\nPilots measure qualified leads, response time, sales effort, quotation conversion and acquisition cost. Specialists review export controls, sanctions, customs, tax, certification and local law.',
  },
  {
    type: 'solution', slug: 'ai-cross-border-commerce', category: 'CROSS-BORDER COMMERCE', featured: false, claimScope: 'proposal',
    title: 'AI 跨境电商运营', titleEn: 'AI cross-border commerce operations',
    summary: '从选品和商品页，到广告、客服、订单和售后，让一个商品按市场规则进入多个国家与平台。',
    summaryEn: 'Connect product research and listings to advertising, service, orders and after-sales so products can adapt to multiple markets and platforms.',
    body: '针对独立站、Amazon、AliExpress、TikTok Shop 和区域平台，建立按国家管理的商品知识、品牌规则、禁限售要求、语言资产和客服政策。AI 辅助选品研究、商品页、广告素材、客服和订单协同。\n\n建议从一个目标市场和 10—30 个 SKU 开始，比较上架速度、广告成本、转化率、退款率、履约时效和毛利。只有经过对照验证的结果才能用于决定扩店和增加预算。\n\n价格、库存、退款、广告预算和消费者权益相关动作保留人工批准与回滚。平台规则、税务、知识产权、产品安全和本地仓配需逐市场确认。',
    bodyEn: 'For DTC, Amazon, AliExpress, TikTok Shop and regional marketplaces, maintain market-specific product data, brand rules, restricted-product requirements, language assets and service policies. AI assists research, listings, media, service and order coordination.\n\nStart with one market and 10–30 SKUs. Compare listing time, advertising cost, conversion, refunds, fulfillment and gross margin before expanding stores or budget.\n\nPrice, inventory, refunds, advertising budget and customer-rights actions retain approval and rollback. Platform rules, tax, IP, safety and logistics require market-by-market confirmation.',
  },
  {
    type: 'solution', slug: 'additive-manufacturing', category: 'ADDITIVE MANUFACTURING', featured: false, claimScope: 'proposal',
    title: '3D 打印与按需制造方案', titleEn: 'Additive manufacturing solution',
    summary: '以 AI 辅助设计、工艺规划、报价排产和质量追溯，服务高价值、小批量、复杂结构的制造需求。',
    summaryEn: 'Use AI-assisted design, process planning, quotation, scheduling and traceability for high-value, low-volume and complex parts.',
    body: '优先选择传统工艺交期长、库存成本高、结构复杂或高度定制的零件。系统辅助可制造性检查、拓扑优化、材料与工艺建议、报价排产、批次记录和检测报告整理。\n\n商业模式包括设计服务、打印制造费、材料耗材和年度生产协同服务。试点要对比现有交期、全生命周期成本、零件性能、合格率和认证成本。\n\n医疗、航空航天和安全关键零件必须由合格工程师完成设计签字，并遵守材料、设备、工艺、检测、追溯和行业认证要求。AI 输出不能替代工程责任。',
    bodyEn: 'Prioritize parts with long conventional lead times, high inventory cost, complex geometry or high customization. The system assists manufacturability, topology, material and process selection, quotation, scheduling, batch records and inspection reports.\n\nCommercial models include design fees, print production, materials and managed manufacturing. Compare current lead time, lifecycle cost, performance, yield and certification cost in the pilot.\n\nQualified engineers sign off medical, aerospace and safety-critical designs. Materials, equipment, process, inspection, traceability and sector certification remain mandatory. AI does not replace engineering accountability.',
  },
  {
    type: 'solution', slug: 'ai-creator-economy', category: 'CREATOR ECONOMY', featured: false, claimScope: 'proposal',
    title: 'AI 自媒体与品牌内容系统', titleEn: 'AI creator and brand media system',
    summary: '把选题、脚本、图文视频、数字人、多平台分发、粉丝线索与商业合作连成可度量的内容生意。',
    summaryEn: 'Connect topics, scripts, media, digital presenters, distribution, audience leads and partnerships into a measurable content business.',
    body: '适用于个人 IP、企业账号、专家内容、矩阵账号和海外频道。先建立垂直主题、目标受众、品牌口径、素材权限和发布节奏，再用 AI 辅助选题、脚本、图文视频、数字人和多平台改编。\n\n常见收入包括代运营、工具订阅、广告商单、电商佣金、知识产品和线索转化。建议连续 30 天运营一个垂直主题，记录有效播放、互动、留资、获客成本、内容成本和持续产能。\n\n不制造虚假身份、虚假销量或未经授权的数字人。广告、带货、医疗、金融和未成年人相关内容按平台及监管规则进行标识、审核和留档。',
    bodyEn: 'Suitable for personal IP, corporate accounts, expert media, account networks and international channels. Define the niche, audience, brand voice, media permissions and cadence before using AI for topics, scripts, visual media, digital presenters and repurposing.\n\nRevenue can include managed operations, subscriptions, brand deals, commerce commissions, knowledge products and leads. Run a 30-day focused pilot and measure qualified views, engagement, leads, acquisition cost, content cost and sustainable output.\n\nDo not create deceptive identities, fake sales or unauthorized digital humans. Advertising, commerce, health, finance and minors-related content require disclosure, review and records.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-video-2026', category: 'MARKET SIGNAL · AI VIDEO', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Kuaishou Technology · Q1 2026 Results', sourceUrl: 'https://ir.kuaishou.com/node/11461/pdf', sourceDate: '2026-05-27',
    title: 'AI 视频、漫剧与短剧：内容生产正在形成收入', titleEn: 'AI video, comics and short drama: production is monetizing',
    summary: '快手披露可灵 AI 2026 年第一季度收入超过 6.5 亿元，同比增长超过 300%；漫剧单日营销消耗峰值超过 2,000 万元。',
    summaryEn: 'Kuaishou reported Kling AI Q1 2026 revenue above RMB650M, up more than 300%, while comic-style short plays exceeded RMB20M in peak daily marketing spend.',
    body: '快手 2026 年第一季度业绩显示，可灵 AI 收入超过 6.5 亿元，同比增长超过 300%，3 月年化收入运行率约 5 亿美元。官方披露同时指出，AI 降低了漫剧制作成本和创作门槛，截至 2026 年 3 月，快手漫剧单日营销消耗峰值超过 2,000 万元。\n\n这为 AI 视频工具、团队协作、内容制作、IP 运营和发行服务提供了明确的付费信号。对 CCT 的启示是把模型调用升级为版权清晰、角色一致、可复用、可分发的制作流程。\n\n单个内容项目应通过制作成本、完播率、付费转化和版权风险决定是否扩量。',
    bodyEn: 'Kuaishou reported Kling AI Q1 2026 revenue above RMB650 million, up more than 300%, and a March annualized revenue run rate of about USD500 million. It also reported peak daily marketing spend above RMB20 million for comic-style short plays by March 2026.\n\nThe signal supports paid demand for AI video tools, team workflows, production, IP operations and distribution. CCT therefore focuses on rights-cleared, consistent, reusable and distributable production rather than isolated generation.\n\nScale each project only after reviewing unit cost, completion, paid conversion and rights risk.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-cross-border-2026', category: 'MARKET SIGNAL · AI COMMERCE', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Alibaba Group · June Quarter 2026 Results', sourceUrl: 'https://www.alibabagroup.com/zh-HK/document-2026456290057781248', sourceDate: '2026-08-20',
    title: 'AI 跨境电商：从生成内容转向运营智能体', titleEn: 'AI cross-border commerce: from content to operating agents',
    summary: '阿里巴巴披露商家智能体已覆盖上架、店铺管理、营销和客服自动化；速卖通当季实现经营利润。',
    summaryEn: 'Alibaba reported merchant agents across listings, store operations, marketing and service, while AliExpress reached operating profit in the quarter.',
    body: '阿里巴巴 2026 年 6 月季度业绩披露，商家端智能体能力覆盖产品上架、店铺管理、营销和客服流程；速卖通通过物流优化和成本效率提升实现经营利润。\n\n商业机会不只在批量生成商品文案，而在商品知识、渠道规则、广告、客服、订单、物流和售后的端到端协同。对外贸企业，先用一个市场和有限 SKU 验证毛利与履约，再决定扩张。\n\n落地时重点核算平台费率、广告成本、税务、退货和本地履约。',
    bodyEn: 'Alibaba reported merchant agent capabilities across product listings, store management, marketing and customer service in the June 2026 quarter. AliExpress achieved operating profit through logistics optimization and cost efficiency.\n\nThe opportunity extends beyond product copy into governed catalog data, channel rules, advertising, service, orders, logistics and after-sales. Exporters should validate margin and fulfillment in one market with a limited SKU set before expansion.\n\nImplementation should account for platform fees, acquisition cost, tax, returns and local fulfillment.',
  },
  {
    type: 'insight', slug: 'market-signal-additive-manufacturing-2026', category: 'MARKET SIGNAL · ADDITIVE', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Materialise · Q2 2026 Results', sourceUrl: 'https://materialise.gcs-web.com/news-releases/news-release-details/materialise-reports-second-quarter-and-half-year-2026-results', sourceDate: '2026-08-27',
    title: '3D 打印：高价值机会来自医疗与生产服务', titleEn: '3D printing: value concentrates in medical and production services',
    summary: 'Materialise 披露 2026 年第二季度收入增长 8.1%、调整后 EBITDA 增长 15.7%，医疗业务收入增长 12.2%。',
    summaryEn: 'Materialise reported Q2 2026 revenue growth of 8.1%, adjusted EBITDA growth of 15.7% and 12.2% growth in medical revenue.',
    body: 'Materialise 2026 年第二季度收入同比增长 8.1% 至 7,007 万欧元，调整后 EBITDA 增长 15.7%，医疗业务收入增长 12.2%，医疗业务调整后 EBITDA 率为 31.3%。\n\n证据表明，增材制造的高价值方向更接近医疗、软件、生产服务和复杂零部件，而不是泛化地销售桌面打印机。CCT 可从 AI 设计辅助、订单与排产协同、质量追溯和按需制造切入。\n\n项目可行性取决于材料、设备、良率、认证、订单结构与交付能力。',
    bodyEn: 'Materialise reported Q2 2026 revenue up 8.1% to EUR70.07 million, adjusted EBITDA up 15.7%, medical revenue up 12.2% and a 31.3% adjusted EBITDA margin in the medical segment.\n\nThe evidence points to medical, software, production services and complex parts as higher-value areas than generic desktop printer sales. CCT can enter through AI design assistance, order and schedule coordination, traceability and on-demand production.\n\nProject economics depend on materials, equipment, yield, certification, order mix and delivery capability.',
  },
  {
    type: 'insight', slug: 'market-signal-creator-economy-2025', category: 'MARKET SIGNAL · CREATOR ECONOMY', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'YouTube · Made on YouTube 2025', sourceUrl: 'https://blog.youtube/news-and-events/made-on-youtube-2025/', sourceDate: '2025-09-16',
    title: 'AI 自媒体：创作工具正在接入成熟收入生态', titleEn: 'AI creator media: creation tools enter a mature revenue ecosystem',
    summary: 'YouTube 披露过去四年向创作者、艺术家和媒体公司支付超过 1,000 亿美元，并持续把 AI 用于 Shorts 与商业合作。',
    summaryEn: 'YouTube reported more than USD100B paid to creators, artists and media companies over four years while expanding AI across Shorts and brand partnerships.',
    body: 'YouTube 在 2025 年 Made on YouTube 发布中披露，过去四年向创作者、艺术家和媒体公司支付超过 1,000 亿美元，并继续将 AI 用于 Shorts 创作、商品标记和品牌合作。\n\n这说明 AI 自媒体的商业价值来自成熟的广告、商单、电商、会员和知识产品生态。CCT 应提供选题、制作、分发、线索与效果复盘的一体化运营，而不是只销售文案生成。\n\n平台支付总额不代表单个创作者收入或利润。账号定位、原创能力、平台规则、流量成本和商业转化决定实际结果。',
    bodyEn: 'At Made on YouTube 2025, YouTube reported more than USD100 billion paid to creators, artists and media companies over four years, while expanding AI for Shorts, product tagging and brand partnerships.\n\nThe signal shows that creator value sits in mature advertising, brand, commerce, membership and knowledge-product ecosystems. CCT should connect ideas, production, distribution, leads and measurement rather than sell copy generation alone.\n\nPlatform-wide payouts do not predict individual income or profit. Positioning, originality, platform rules, acquisition and conversion determine results.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-public-services-2026', category: 'MARKET SIGNAL · PUBLIC SERVICES', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: '国家网信办 · 政务领域人工智能大模型部署应用指引', sourceUrl: 'https://app.www.gov.cn/govdata/gov/202510/11/538227/article.html', sourceDate: '2025-10-11',
    title: 'AI 公共服务：建设、运营与按量服务出现明确路径', titleEn: 'AI public services: implementation and managed usage paths emerge',
    summary: '官方指引提出政务智能问答、辅助办理和政策匹配，并探索企业建设运营、政府购买服务和按使用情况结算。',
    summaryEn: 'Official guidance covers public-service answers, assisted processing and policy matching, with enterprise operations, government procurement and usage-based settlement.',
    body: '《政务领域人工智能大模型部署应用指引》列出智能问答、辅助办理、政策匹配、智能派单、监测巡检和辅助决策等场景，并提出企业建设运营、政府购买服务和按使用情况结算的模式。\n\n这给 AI 公共服务提供了可持续商业路径，但核心要求是权威数据、集约复用、全周期管理、内容审核、安全监测和辅助型定位。\n\n落地时需与项目主管部门确认采购、部署、数据处理、算法备案、保密和验收要求。',
    bodyEn: 'China’s guidance for large models in government covers assisted answers, service processing, policy matching, routing, monitoring and decision support, and describes enterprise operations, government procurement and usage-based settlement.\n\nThis creates a sustainable service path while requiring authoritative data, shared infrastructure, lifecycle management, content review, security monitoring and an assistive role.\n\nImplementation requires confirmation of procurement, deployment, data, filing, confidentiality and acceptance requirements with the responsible authority.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-infrastructure-2026', category: 'MARKET SIGNAL · INFRASTRUCTURE', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'NVIDIA Investor Relations', sourceUrl: 'https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-Second-Quarter-Fiscal-2027/', sourceDate: '2026-08-26',
    title: 'AI 基础设施：收入与毛利证据最强的商业主航道', titleEn: 'AI infrastructure: the strongest current revenue signal',
    summary: 'NVIDIA 披露 FY2027 Q2 数据中心收入 890 亿美元，同比增长 117%，显示 AI 基础设施需求持续增强。',
    summaryEn: 'NVIDIA reported $89B in Q2 FY2027 data-center revenue, up 117% year over year, indicating sustained AI infrastructure demand.',
    body: 'NVIDIA 于 2026 年 8 月 26 日披露，FY2027 第二季度数据中心收入为 890 亿美元，同比增长 117%，公司 GAAP 毛利率为 75%。\n\n这说明推理算力、网络、系统软件和数据中心交付仍具强商业化强度。对 CCT 的产品启示是：价值不能停留在转售 GPU，而应覆盖资源编排、推理效率、可观测、FinOps、SLA 与持续运维。\n\n项目机会应结合客户负载、资源供给、供电条件、单位任务成本与服务水平验证。',
    bodyEn: 'On 26 August 2026, NVIDIA reported Q2 FY2027 data-center revenue of $89 billion, up 117% year over year, and a company GAAP gross margin of 75%.\n\nThe signal supports continued demand for inference compute, networking, systems software and data-center delivery. For CCT, the product implication is to extend beyond GPU resale into orchestration, inference efficiency, observability, FinOps, service levels and managed operations.\n\nProject opportunities should be validated against workloads, resource supply, power, unit cost and service levels.',
  },
  {
    type: 'insight', slug: 'market-signal-enterprise-agents-2026', category: 'MARKET SIGNAL · AGENTS', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Salesforce Investor Relations', sourceUrl: 'https://investor.salesforce.com/news/news-details/2026/Salesforce-Delivers-Record-Second-Quarter-Fiscal-2027-Results/default.aspx', sourceDate: '2026-08-26',
    title: '企业智能体：从对话入口转向可计量的业务动作', titleEn: 'Enterprise agents: from chat to metered work',
    summary: 'Salesforce 披露 Agentforce ARR 超过 15 亿美元、同比增长 240%，显示生产级智能体正形成清晰付费需求。',
    summaryEn: 'Salesforce reported Agentforce ARR above $1.5B, up 240%, indicating paid demand for production agents.',
    body: 'Salesforce 于 2026 年 8 月 26 日披露，Agentforce 年度经常性收入超过 15 亿美元，同比增长 240%；Agentforce 与 Data 360 合计 ARR 接近 39 亿美元。\n\n商业信号指向“席位加动作/消耗”的混合计费，以及企业数据、工具、治理和结果度量的一体化。CCT AgentOS 因此以任务完成、人工复核、延迟和单位成本为核心指标。\n\n企业智能体项目应通过真实任务量、完成率、人工介入和单位成本验证商业价值。',
    bodyEn: 'On 26 August 2026, Salesforce reported Agentforce ARR above $1.5 billion, up 240% year over year, and combined Agentforce and Data 360 ARR near $3.9 billion.\n\nThe signal points to hybrid seat-plus-action or consumption pricing, together with enterprise data, tools, governance and outcome measurement. CCT AgentOS therefore focuses on task completion, human review, latency and unit cost.\n\nEnterprise-agent value should be validated through real task volume, completion, human intervention and unit cost.',
  },
  {
    type: 'insight', slug: 'market-signal-industry-ai-2026', category: 'MARKET SIGNAL · INDUSTRY AI', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Palantir Q2 2026 Form 10-Q', sourceUrl: 'https://investors.palantir.com/files/2026%20Q2%20PLTR%2010-Q.pdf', sourceDate: '2026-08-03',
    title: '行业 AI：业务语义、数据与工作流形成高价值合同', titleEn: 'Industry AI: semantics, data and workflows drive value',
    summary: 'Palantir 披露 2026 Q2 商业收入同比增长 110%、毛利率 85%，体现行业操作平台的商业质量。',
    summaryEn: 'Palantir reported Q2 2026 commercial revenue growth of 110% and an 85% gross margin, a strong industry-platform signal.',
    body: 'Palantir 在 2026 年第二季度 10-Q 中披露，季度收入 19.35 亿美元，同比增长 93%；商业收入 9.45 亿美元，同比增长 110%；毛利率 85%。\n\n市场信号表明，连接业务语义、受治理数据、工作流与执行型智能体的平台，可能比通用聊天入口更容易形成高价值项目。CCT 行业方案因此采用“输入、决策、动作、证据、KPI”的闭环结构。\n\n行业 AI 项目的价格与价值，应通过业务指标、合同范围和验收数据逐项确认。',
    bodyEn: 'Palantir reported Q2 2026 revenue of $1.935 billion, up 93%, commercial revenue of $945 million, up 110%, and an 85% gross margin.\n\nThe signal suggests platforms connecting business semantics, governed data, workflows and executing agents can support high-value projects more effectively than a generic chat interface. CCT industry solutions therefore use an input, decision, action, evidence and KPI loop.\n\nIndustry AI pricing and value should be confirmed through business metrics, contract scope and acceptance evidence.',
  },
  {
    type: 'insight', slug: 'market-signal-energy-ai-2030', category: 'MARKET SIGNAL · ENERGY', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'International Energy Agency · Energy and AI', sourceUrl: 'https://www.iea.org/reports/energy-and-ai/executive-summary', sourceDate: '2025-04-10',
    title: '算能协同：AI 增长把供电与效率推到交付前线', titleEn: 'Compute and energy: power becomes a delivery constraint',
    summary: 'IEA 基准情景预计全球数据中心用电到 2030 年增至约 945 TWh，较当前水平翻倍以上。',
    summaryEn: 'The IEA base case projects global data-center electricity use to exceed double today’s level, reaching about 945 TWh by 2030.',
    body: '国际能源署《Energy and AI》基准情景预计，全球数据中心用电到 2030 年增至约 945 TWh，较当前水平翻倍以上；AI 是增长的最重要驱动因素。\n\n这使供电、并网、散热、容量和能源成本成为 AI 系统交付的一部分。CCT Green Compute 将利用率、队列、功耗、热风险、容量与成本纳入同一运行视图。\n\n容量规划需同时评估硬件效率、部署速度、电网条件、散热与能源成本。',
    bodyEn: 'The International Energy Agency’s Energy and AI base case projects global data-center electricity consumption at about 945 TWh in 2030, more than double today’s level, with AI the most important driver.\n\nPower access, grids, cooling, capacity and energy cost therefore become part of AI delivery. CCT Green Compute brings utilization, queues, power, thermal risk, capacity and cost into one operating view.\n\nCapacity planning should assess hardware efficiency, deployment pace, grid conditions, cooling and energy cost together.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-governance-2026', category: 'MARKET SIGNAL · GOVERNANCE', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'European Commission · AI Act enforcement', sourceUrl: 'https://digital-strategy.ec.europa.eu/en/news/commission-starts-enforcing-ai-act-rules-and-new-transparency-requirements-2-august', sourceDate: '2026-07-31',
    title: 'AI 治理：透明、标识与审计从建议进入执行', titleEn: 'AI governance: transparency and audit enter enforcement',
    summary: '欧盟委员会确认自 2026 年 8 月 2 日开始执行相关 AI Act 权力与透明要求。',
    summaryEn: 'The European Commission confirmed enforcement powers and relevant AI Act transparency rules from 2 August 2026.',
    body: '欧盟委员会于 2026 年 7 月 31 日说明，从 8 月 2 日起开始执行相关 AI Act 权力与透明要求：特定交互式 AI 需要告知用户其 AI 身份，生成或篡改内容适用标识与机器可读要求。\n\n这使智能体登记、责任人、运行追踪、内容标识、评测门禁、人工审批和事件响应成为跨境系统的设计输入。\n\n法规适用取决于角色、市场、用途和系统风险。官网信息不构成法律意见，项目应由合格法务确认适用条款和时间。',
    bodyEn: 'On 31 July 2026, the European Commission stated that relevant AI Act enforcement powers and transparency requirements would apply from 2 August. Certain interactive AI must disclose that users are dealing with AI, while generated or manipulated content is subject to disclosure and machine-readable marking rules.\n\nAgent registries, ownership, traces, content disclosure, evaluation gates, human approval and incident response therefore become design inputs for cross-border systems.\n\nApplicability depends on role, market, use and risk. This site is not legal advice; qualified counsel should confirm project obligations and dates.',
  },
  {
    type: 'insight', slug: 'market-signal-physical-ai-2025', category: 'MARKET SIGNAL · PHYSICAL AI', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'International Federation of Robotics · World Robotics 2025', sourceUrl: 'https://ifr.org/img/worldrobotics/Executive_Summary_WR_2025_Industrial_Robots.pdf', sourceDate: '2025-09-25',
    title: '具身智能：机器人存量巨大，但 AI 盈利证据仍需分开看', titleEn: 'Physical AI: large robot adoption, distinct AI economics',
    summary: 'IFR 统计 2024 年全球新增工业机器人约 54.2 万台、运营存量约 466 万台，为视觉、仿真和边缘推理提供广泛场景。',
    summaryEn: 'IFR counted about 542,000 industrial robot installations and 4.66M operational units in 2024, creating broad settings for vision, simulation and edge inference.',
    body: '国际机器人联合会《World Robotics 2025》统计，2024 年全球新增工业机器人约 54.2 万台，运营存量约 466 万台；中国占全球新增安装的 54%。\n\n机器人部署基础为视觉、仿真、边缘推理与智能任务规划提供了场景，但工业机器人安装量不能等同于具身大模型收入、利润或自动化收益。\n\n因此 CCT 将 Physical AI 定位为联合实验室与阶段化试点，在仿真、安全围栏和现场验收后再决定扩展。',
    bodyEn: 'The International Federation of Robotics counted roughly 542,000 new industrial robot installations and about 4.66 million operational units in 2024; China accounted for 54% of new installations.\n\nThis installed base creates opportunities for vision, simulation, edge inference and intelligent planning, but robot installations are not embodied-model revenue, profit or automation returns.\n\nCCT therefore positions Physical AI as a joint lab with gated pilots, requiring simulation, safety controls and field acceptance before scale-up.',
  },
];
