export const initialSettings = {
  brandName: 'CCT 算链集团',
  heroTitle: '让智能，\n成为生产力。',
  heroTitleEn: 'Intelligence.\nPut to work.',
  heroSubtitle: '连接 AI、算力与产业场景。从一个可验证的业务问题出发，构建可部署、可治理、可持续进化的智能系统。',
  heroSubtitleEn: 'Connect AI, compute and industry. Start with a measurable business problem. Build intelligent systems that can be deployed, governed and improved.',
  contactEmail: 'contact@cct.example',
};

// These are editable capability descriptions, not customer references or claims of completed delivery.
export const initialContent = [
  {
    type: 'service', slug: 'ai-transformation', category: 'AI TRANSFORMATION', featured: true,
    title: '企业 AI 转型', titleEn: 'Enterprise AI transformation',
    summary: '让 AI 进入真实业务流程，以明确的基线、责任与验收标准推进组织升级。',
    summaryEn: 'Bring AI into operational workflows with clear baselines, ownership and acceptance criteria.',
    body: '从业务问题开始，而不是从采购工具开始。梳理高频流程、数据可用性与组织责任，选择能够测量价值的首批场景。\n\n交付路径包括：现状诊断与流程地图、场景优先级与收益假设、受控试点、评估与人工复核、分阶段推广。每个阶段明确业务负责人、输入数据、验收证据和停止条件。\n\n适用场景：企业知识检索、客户服务辅助、经营分析、内容生产与运营协同。涉及人事、财务审批或其他重大决定时，保留明确的人工决策与审计机制。具体能力、范围与服务水平在项目评估后确认。',
    bodyEn: 'Begin with a business problem, not a tool purchase. Map frequent workflows, data readiness and decision ownership before selecting measurable pilot use cases.\n\nThe proposed delivery path includes discovery, a workflow map, prioritized opportunities, a controlled pilot, human-reviewed evaluation and phased rollout. Each stage defines accountable owners, data inputs, acceptance evidence and stop conditions.\n\nPotential applications include enterprise knowledge retrieval, service assistance, operational analysis and content operations. Consequential HR, financial or other decisions retain human accountability and audit controls. Scope and service levels are confirmed through project assessment.',
  },
  {
    type: 'service', slug: 'agent-systems', category: 'AGENT SYSTEMS', featured: true,
    title: '智能体与工作流', titleEn: 'Agents & intelligent workflows',
    summary: '把模型能力转化为可编排的任务执行，让每一次调用都有权限、记录与边界。',
    summaryEn: 'Turn model capabilities into orchestrated work with explicit permissions, traceability and boundaries.',
    body: '面向业务任务设计智能体：明确目标、可调用工具、数据权限和人机交接点。知识检索、结构化生成与业务系统连接在同一流程中完成，避免孤立的对话窗口。\n\n规划能力包括工具白名单、审批节点、运行追踪、重试与超时、费用限额、离线评测、失败回退和版本管理。外部写入、交易与高影响操作默认设置人工确认。\n\n从单个流程的受控试点逐步扩展。以任务完成率、准确性、人工介入率、端到端耗时与单位成本评估系统，而不以演示效果代替业务结果。',
    bodyEn: 'Design agents around a business task: define the objective, available tools, data permissions and human handoff points. Combine retrieval, structured generation and business-system integration within a coherent workflow.\n\nPlanned controls include tool allowlists, approval steps, run traces, retries and timeouts, spending limits, offline evaluation, fallbacks and versioning. External writes, transactions and consequential actions require human approval by default.\n\nExpand from one controlled workflow. Evaluate completion, correctness, intervention rate, end-to-end time and unit cost rather than relying on a compelling demonstration.',
  },
  {
    type: 'service', slug: 'compute-infrastructure', category: 'COMPUTE INFRASTRUCTURE', featured: true,
    title: '算力与基础设施', titleEn: 'Compute & infrastructure',
    summary: '围绕负载、成本与数据边界，设计从开发验证到生产运行的算力架构。',
    summaryEn: 'Design compute architecture around workload requirements, cost and data boundaries.',
    body: '根据模型规模、吞吐、延迟、部署区域与数据敏感度评估算力需求，比较公有云、私有化与混合部署的适用条件。\n\n架构规划覆盖模型服务、任务调度、资源配额、监控告警、容量评估、备份恢复与成本归集。算力资源的实际供应、价格、可用区和服务水平以具体供应商及合同为准。\n\n先用代表性负载建立性能与成本基线，再决定优化和扩容。对外展示的任何运行指标应来自经过验证的真实监控；网站不以模拟节点数或演示动画宣称基础设施规模。',
    bodyEn: 'Assess compute needs using model size, throughput, latency, deployment region and data sensitivity. Compare public cloud, private and hybrid deployment against concrete requirements.\n\nArchitecture planning covers model serving, scheduling, resource quotas, monitoring, capacity, recovery and cost allocation. Actual supply, pricing, regions and service levels depend on the selected provider and contract.\n\nEstablish performance and cost baselines using representative workloads before optimization or expansion. Public operating metrics must come from verified monitoring; visual demonstrations do not represent infrastructure scale.',
  },
  {
    type: 'service', slug: 'trusted-data', category: 'TRUSTED DATA', featured: true,
    title: '可信数据与协作', titleEn: 'Trusted data & collaboration',
    summary: '把数据治理、可追溯机制与适用的分布式技术连接起来，建立协作基础。',
    summaryEn: 'Connect data governance, traceability and fit-for-purpose distributed technology.',
    body: '先确认数据权属、授权与质量，再讨论跨组织协作的技术路径。通过数据目录、分级分类、访问控制和生命周期管理建立可用的数据基础。\n\n对确有多方协作与存证需求的场景，评估签名、可信时间戳、审计日志或分布式账本的适用性。技术选择服从业务必要性，不将上链等同于数据真实或合规。\n\n涉及设备网络、DePIN 或其他分布式资源协同时，先验证设备身份、计量可信度、资源质量与运维机制；经济机制与商业模式需独立评估。',
    bodyEn: 'Establish data ownership, authorization and quality before selecting a cross-organization collaboration architecture. Build a usable foundation with cataloging, classification, access controls and lifecycle management.\n\nWhere multiparty collaboration and evidence are necessary, assess signatures, trusted timestamps, audit logs or distributed ledgers. Technology follows business necessity; recording data on a ledger does not prove its accuracy or compliance.\n\nFor device networks, DePIN or distributed resources, validate identity, metering, quality and operations first. Economic mechanisms and business models require separate assessment.',
  },
  {
    type: 'solution', slug: 'enterprise-knowledge', category: 'ENTERPRISE', featured: true,
    title: '企业知识与经营协同', titleEn: 'Enterprise knowledge & operations',
    summary: '连接分散的知识与流程，为员工提供有依据、可追溯的业务辅助。',
    summaryEn: 'Connect fragmented knowledge and workflows to deliver evidence-based operational assistance.',
    body: '典型问题：资料分散、检索困难、口径不一致，以及重复汇总造成的协作成本。\n\n方案方向：建立授权文档索引，保留来源引用与版本信息；按照岗位权限检索知识；结合结构化模板辅助制作报告、任务清单与经营摘要。\n\n试点验证：选取一个部门和明确的知识范围，记录检索成功率、引用准确率、回答拒绝率、处理时长与用户反馈。敏感资料遵循权限继承与最小访问原则。此页面为方案描述，实际系统范围需经需求评估。',
    bodyEn: 'Typical challenges include fragmented documentation, difficult retrieval, inconsistent answers and repetitive reporting.\n\nThe proposed approach indexes authorized documents with source references and version context, applies role-based access and supports reports, task lists and operating summaries through structured templates.\n\nA pilot starts with one department and a defined corpus. Evaluation measures retrieval success, citation accuracy, refusal behavior, handling time and feedback. Sensitive documents retain inherited permissions and least-privilege access. This is a solution description; implementation scope requires assessment.',
  },
  {
    type: 'solution', slug: 'education-intelligence', category: 'EDUCATION', featured: true,
    title: '教育与人才发展', titleEn: 'Education & workforce development',
    summary: '支持教学准备、知识服务与运营协同，让教师与管理者掌握最终判断。',
    summaryEn: 'Support teaching preparation, knowledge services and operations while preserving human judgment.',
    body: '围绕教学准备、课程资料检索、行政流程与人才培养支持设计可控的 AI 辅助工作流。\n\n实施边界：学生信息、未成年人数据和教学资料按敏感程度分级处理；教学评价、成绩、资格认定及人事决定保留人工决策。模型输出应由具备相应责任的人员复核。\n\n分阶段验证：先测量现有流程成本与质量，再开展小范围试点，对比节省的工时、质量变化与新增复核成本。外部案例仅作为试点假设，不直接转换为裁员承诺或保证收益。',
    bodyEn: 'Design controlled AI assistance for lesson preparation, curriculum retrieval, administrative workflows and workforce development.\n\nBoundaries: classify student information, minors’ data and teaching materials by sensitivity. Teaching evaluation, grades, certification and employment decisions retain human authority. Accountable staff review generated outputs.\n\nMeasure existing cost and quality before a small pilot. Compare time saved, changes in quality and the additional cost of review. External evidence informs hypotheses; it does not establish guaranteed returns or staffing outcomes.',
  },
  {
    type: 'solution', slug: 'industrial-intelligence', category: 'INDUSTRY', featured: true,
    title: '产业智能与设备协同', titleEn: 'Industrial intelligence',
    summary: '把现场知识、设备数据与业务系统结合，探索可落地的产业 AI 场景。',
    summaryEn: 'Connect operational knowledge, equipment data and business systems for practical industrial AI.',
    body: '以现场问题为入口，评估设备知识检索、维护辅助、质量记录分析与生产运营协同的实际价值。\n\n先检查数据质量、设备接口、网络条件和安全要求，再决定边缘或云端部署。系统接入采用权限隔离，生产控制指令与安全相关操作保留既有控制和审批机制。\n\n试点使用可复核的样本集和明确的验收标准，记录误报、漏报、响应时间与人员反馈。数字化建议需要由现场专业人员验证，不能直接取代设备安全规程。',
    bodyEn: 'Start from an operational problem and assess the value of equipment knowledge retrieval, maintenance assistance, quality-record analysis and workflow coordination.\n\nEvaluate data quality, interfaces, connectivity and safety requirements before choosing edge or cloud deployment. Isolate integration permissions; production-control commands and safety-related actions preserve existing controls and approvals.\n\nUse reviewable samples and explicit acceptance criteria. Track false positives, missed findings, response time and staff feedback. On-site specialists validate recommendations; generated advice does not replace equipment safety procedures.',
  },
  {
    type: 'solution', slug: 'low-altitude-ecosystem', category: 'EMERGING ECOSYSTEMS', featured: true,
    title: '低空经济与分布式网络', titleEn: 'Low-altitude & distributed networks',
    summary: '探索任务协同、数据管理与资源调度，为新兴产业建立可验证的技术路径。',
    summaryEn: 'Explore mission coordination, data management and resource scheduling for emerging industries.',
    body: '面向低空经济与分布式设备协作，探索任务资料管理、设备状态汇聚、运营数据分析和资源调度辅助等技术方向。\n\n项目启动前需明确应用场景、设备能力、必要授权、责任主体与适用的运营规则。网站展示技术方向，不表示已取得飞行、运营或其他特定资质。\n\n先在受控环境验证数据链路、身份认证、故障回退与人员协同。涉及实际设备操作、飞行决策与现场安全时，专业运营人员与既有安全流程保持最终控制。',
    bodyEn: 'Explore mission-document management, device-status aggregation, operational analytics and resource-scheduling assistance for low-altitude and distributed device ecosystems.\n\nDefine the use case, device capabilities, required authorizations, accountable operators and applicable operating rules before a project begins. This page presents technology directions and does not claim flight, operating or other specific qualifications.\n\nValidate data paths, identity, fallback and human coordination in a controlled environment. Qualified operators and established safety processes retain final control of physical operations, flight decisions and field safety.',
  },
  {
    type: 'insight', slug: 'from-ai-demo-to-delivery', category: 'PERSPECTIVES', featured: true,
    title: '从 AI 演示到业务交付，中间还缺什么？', titleEn: 'What turns an AI demo into business delivery?',
    summary: '一条可验证的交付路径，需要同时回答价值、数据、质量、责任与运行五个问题。',
    summaryEn: 'A verifiable delivery path must address value, data, quality, accountability and operations.',
    body: '演示让人看见可能性，交付需要证明可用性。进入真实业务后，系统要面对不完整输入、变化的权限、多样的用户和不可预期的失败。\n\n第一步是建立业务基线：当前耗时、质量、成本与风险分别是多少？第二步是确定评估集与验收标准，覆盖常见任务、边界情况和必须拒绝的请求。第三步是设计人工接管、运行监控与问题回溯。\n\n只有将这些条件与业务目标一起写入交付范围，团队才可能判断系统是否值得扩大应用。这是一篇方法论观点文章，具体结论需要项目实测支持。',
    bodyEn: 'A demo shows possibility; delivery requires evidence of usability. Real workflows introduce incomplete inputs, changing permissions, diverse users and unexpected failures.\n\nFirst establish the operating baseline: current time, quality, cost and risk. Then define evaluation samples and acceptance criteria across normal tasks, edge cases and requests the system must refuse. Finally design human takeover, monitoring and incident traceability.\n\nPutting these conditions alongside business goals makes an expansion decision possible. This article presents a methodology; project-specific conclusions require measurement.',
  },
  {
    type: 'insight', slug: 'compute-that-fits-the-workload', category: 'ENGINEERING', featured: false,
    title: '算力规划，先回答负载问题', titleEn: 'Compute planning begins with the workload',
    summary: '从吞吐、延迟、可用性和数据边界出发，建立可比较的性能与成本基线。',
    summaryEn: 'Build comparable performance and cost baselines around throughput, latency, availability and data boundaries.',
    body: '算力选型不是孤立比较设备参数。模型、上下文长度、并发、量化策略与缓存方式都会改变资源需求。\n\n规划时应选择代表性任务，记录端到端响应时间、有效吞吐、失败率和单位任务成本。再结合部署区域、数据边界、恢复目标与供应条件比较方案。\n\n公开的基准测试可以帮助提出问题，但不能代替自身工作负载测试。容量与成本承诺应建立在双方确认的负载、测量方法和服务水平之上。',
    bodyEn: 'Compute selection is not a standalone comparison of hardware specifications. Models, context length, concurrency, quantization and caching all change resource demand.\n\nUse representative tasks to measure end-to-end latency, useful throughput, failure rate and cost per completed task. Compare options against deployment regions, data boundaries, recovery objectives and resource availability.\n\nPublic benchmarks inform questions but do not replace workload-specific testing. Capacity and cost commitments require agreed workloads, measurement methods and service levels.',
  },
  {
    type: 'insight', slug: 'governance-by-design', category: 'RESPONSIBLE AI', featured: false,
    title: '把治理放进系统设计的第一天', titleEn: 'Build governance into day one',
    summary: '从权限、来源引用、人工复核和审计记录入手，让可信成为具体的系统能力。',
    summaryEn: 'Make trust concrete through permissions, source attribution, human review and auditable records.',
    body: '治理不应是上线后的补充文档。它决定系统能读取哪些资料、调用哪些工具、执行哪些动作，以及出现问题时谁能解释和处理。\n\n在设计阶段确定数据分级、访问控制、保留期限、模型使用范围与人工审批点。对重要输出保留来源与版本，对关键操作记录主体、时间和动作，避免在日志中复制敏感内容。\n\n治理也需要验证：测试越权访问、错误引用、工具误调用和失败回退。明确知道系统何时需要停止与转交给人，是可靠交付的一部分。',
    bodyEn: 'Governance is not an after-launch document. It determines which information a system can access, which tools it can call, which actions it may take and who can explain or resolve failures.\n\nDefine data classification, access, retention, permitted model use and human approval points during design. Preserve source and version context for important outputs, and log actors, timestamps and key actions without unnecessarily duplicating sensitive content.\n\nGovernance also needs testing: unauthorized access, incorrect references, tool misuse and failure recovery. Knowing when to stop and hand control to a person is part of reliable delivery.',
  },
];
