export const initialSettings = {
  brandName: 'CCT 算链集团',
  heroTitle: '连接算力、数据与智能体，\n持续产生业务结果。',
  heroTitleEn: 'Compute, data and agents.\nEngineered for outcomes.',
  heroSubtitle: 'CCT AI 产业计算网络，从推理基础设施、企业智能体到行业系统与可信治理，构建可评测、可审计、可计量的生产级路径。',
  heroSubtitleEn: 'CCT AI Industrial Network connects inference infrastructure, enterprise agents, industry systems and trusted governance into a measurable path to production.',
  contactEmail: 'contact@cct.example',
};

// These are editable capability descriptions, not customer references or claims of completed delivery.
export const initialContent = [
  {
    type: 'service', slug: 'ai-transformation', category: 'AI TRANSFORMATION', featured: true,
    title: '企业 AI 转型', titleEn: 'Enterprise AI transformation',
    summary: '让 AI 进入真实业务流程，以明确的基线、责任与验收标准推进组织升级。',
    summaryEn: 'Bring AI into operational workflows with clear baselines, ownership and acceptance criteria.',
    body: '从业务问题开始，而不是从采购工具开始。梳理高频流程、数据可用性与组织责任，选择能够测量价值的首批场景。\n\n交付路径包括：现状诊断与流程地图、场景优先级与收益假设、受控试点、评估与人工复核、分阶段推广。每个阶段明确业务负责人、输入数据、验收证据和停止条件。\n\n适用场景：企业知识检索、客户服务辅助、经营分析、内容生产与运营协同。涉及人事、财务审批或其他重大决定时，保留明确的人工决策与审计机制。具体能力、范围与服务水平在项目评估后确认。',
    bodyEn: 'Begin with a business problem, not a tool purchase. Map frequent workflows, data readiness and decision ownership before selecting measurable pilot use cases.\n\nThe proposed delivery path includes discovery, a workflow map, prioritized opportunities, a controlled pilot, human-reviewed evaluation and phased rollout. Each stage defines accountable owners, data inputs, acceptance evidence and stop conditions.\n\nPotential applications include enterprise knowledge retrieval, service assistance, operational analysis and content operations. Consequential HR, financial or other decisions retain human accountability and audit controls. Scope and service levels are confirmed through project assessment.',
  },
  {
    type: 'service', slug: 'agent-systems', category: 'AGENT SYSTEMS', featured: true,
    title: '智能体与工作流', titleEn: 'Agents & intelligent workflows',
    summary: '把模型能力转化为可编排的任务执行，让每一次调用都有权限、记录与边界。',
    summaryEn: 'Turn model capabilities into orchestrated work with explicit permissions, traceability and boundaries.',
    body: '面向业务任务设计智能体：明确目标、可调用工具、数据权限和人机交接点。知识检索、结构化生成与业务系统连接在同一流程中完成，避免孤立的对话窗口。\n\n规划能力包括工具白名单、审批节点、运行追踪、重试与超时、费用限额、离线评测、失败回退和版本管理。外部写入、交易与高影响操作默认设置人工确认。\n\n从单个流程的受控试点逐步扩展。以任务完成率、准确性、人工介入率、端到端耗时与单位成本评估系统，而不以演示效果代替业务结果。',
    bodyEn: 'Design agents around a business task: define the objective, available tools, data permissions and human handoff points. Combine retrieval, structured generation and business-system integration within a coherent workflow.\n\nPlanned controls include tool allowlists, approval steps, run traces, retries and timeouts, spending limits, offline evaluation, fallbacks and versioning. External writes, transactions and consequential actions require human approval by default.\n\nExpand from one controlled workflow. Evaluate completion, correctness, intervention rate, end-to-end time and unit cost rather than relying on a compelling demonstration.',
  },
  {
    type: 'service', slug: 'compute-infrastructure', category: 'COMPUTE INFRASTRUCTURE', featured: true,
    title: '算力与基础设施', titleEn: 'Compute & infrastructure',
    summary: '围绕负载、成本与数据边界，设计从开发验证到生产运行的算力架构。',
    summaryEn: 'Design compute architecture around workload requirements, cost and data boundaries.',
    body: '根据模型规模、吞吐、延迟、部署区域与数据敏感度评估算力需求，比较公有云、私有化与混合部署的适用条件。\n\n架构规划覆盖模型服务、任务调度、资源配额、监控告警、容量评估、备份恢复与成本归集。算力资源的实际供应、价格、可用区和服务水平以具体供应商及合同为准。\n\n先用代表性负载建立性能与成本基线，再决定优化和扩容。对外展示的任何运行指标应来自经过验证的真实监控；网站不以模拟节点数或演示动画宣称基础设施规模。',
    bodyEn: 'Assess compute needs using model size, throughput, latency, deployment region and data sensitivity. Compare public cloud, private and hybrid deployment against concrete requirements.\n\nArchitecture planning covers model serving, scheduling, resource quotas, monitoring, capacity, recovery and cost allocation. Actual supply, pricing, regions and service levels depend on the selected provider and contract.\n\nEstablish performance and cost baselines using representative workloads before optimization or expansion. Public operating metrics must come from verified monitoring; visual demonstrations do not represent infrastructure scale.',
  },
  {
    type: 'service', slug: 'trusted-data', category: 'TRUSTED DATA', featured: true,
    title: '可信数据与协作', titleEn: 'Trusted data & collaboration',
    summary: '把数据治理、可追溯机制与适用的分布式技术连接起来，建立协作基础。',
    summaryEn: 'Connect data governance, traceability and fit-for-purpose distributed technology.',
    body: '先确认数据权属、授权与质量，再讨论跨组织协作的技术路径。通过数据目录、分级分类、访问控制和生命周期管理建立可用的数据基础。\n\n对确有多方协作与存证需求的场景，评估签名、可信时间戳、审计日志或分布式账本的适用性。技术选择服从业务必要性，不将上链等同于数据真实或合规。\n\n涉及设备网络、DePIN 或其他分布式资源协同时，先验证设备身份、计量可信度、资源质量与运维机制；经济机制与商业模式需独立评估。',
    bodyEn: 'Establish data ownership, authorization and quality before selecting a cross-organization collaboration architecture. Build a usable foundation with cataloging, classification, access controls and lifecycle management.\n\nWhere multiparty collaboration and evidence are necessary, assess signatures, trusted timestamps, audit logs or distributed ledgers. Technology follows business necessity; recording data on a ledger does not prove its accuracy or compliance.\n\nFor device networks, DePIN or distributed resources, validate identity, metering, quality and operations first. Economic mechanisms and business models require separate assessment.',
  },
  {
    type: 'solution', slug: 'enterprise-knowledge', category: 'ENTERPRISE', featured: true,
    title: '企业知识与经营协同', titleEn: 'Enterprise knowledge & operations',
    summary: '连接分散的知识与流程，为员工提供有依据、可追溯的业务辅助。',
    summaryEn: 'Connect fragmented knowledge and workflows to deliver evidence-based operational assistance.',
    body: '典型问题：资料分散、检索困难、口径不一致，以及重复汇总造成的协作成本。\n\n方案方向：建立授权文档索引，保留来源引用与版本信息；按照岗位权限检索知识；结合结构化模板辅助制作报告、任务清单与经营摘要。\n\n试点验证：选取一个部门和明确的知识范围，记录检索成功率、引用准确率、回答拒绝率、处理时长与用户反馈。敏感资料遵循权限继承与最小访问原则。此页面为方案描述，实际系统范围需经需求评估。',
    bodyEn: 'Typical challenges include fragmented documentation, difficult retrieval, inconsistent answers and repetitive reporting.\n\nThe proposed approach indexes authorized documents with source references and version context, applies role-based access and supports reports, task lists and operating summaries through structured templates.\n\nA pilot starts with one department and a defined corpus. Evaluation measures retrieval success, citation accuracy, refusal behavior, handling time and feedback. Sensitive documents retain inherited permissions and least-privilege access. This is a solution description; implementation scope requires assessment.',
  },
  {
    type: 'solution', slug: 'education-intelligence', category: 'EDUCATION', featured: true,
    title: '教育与人才发展', titleEn: 'Education & workforce development',
    summary: '支持教学准备、知识服务与运营协同，让教师与管理者掌握最终判断。',
    summaryEn: 'Support teaching preparation, knowledge services and operations while preserving human judgment.',
    body: '围绕教学准备、课程资料检索、行政流程与人才培养支持设计可控的 AI 辅助工作流。\n\n实施边界：学生信息、未成年人数据和教学资料按敏感程度分级处理；教学评价、成绩、资格认定及人事决定保留人工决策。模型输出应由具备相应责任的人员复核。\n\n分阶段验证：先测量现有流程成本与质量，再开展小范围试点，对比节省的工时、质量变化与新增复核成本。外部案例仅作为试点假设，不直接转换为裁员承诺或保证收益。',
    bodyEn: 'Design controlled AI assistance for lesson preparation, curriculum retrieval, administrative workflows and workforce development.\n\nBoundaries: classify student information, minors’ data and teaching materials by sensitivity. Teaching evaluation, grades, certification and employment decisions retain human authority. Accountable staff review generated outputs.\n\nMeasure existing cost and quality before a small pilot. Compare time saved, changes in quality and the additional cost of review. External evidence informs hypotheses; it does not establish guaranteed returns or staffing outcomes.',
  },
  {
    type: 'solution', slug: 'industrial-intelligence', category: 'INDUSTRY', featured: true,
    title: '产业智能与设备协同', titleEn: 'Industrial intelligence',
    summary: '把现场知识、设备数据与业务系统结合，探索可落地的产业 AI 场景。',
    summaryEn: 'Connect operational knowledge, equipment data and business systems for practical industrial AI.',
    body: '以现场问题为入口，评估设备知识检索、维护辅助、质量记录分析与生产运营协同的实际价值。\n\n先检查数据质量、设备接口、网络条件和安全要求，再决定边缘或云端部署。系统接入采用权限隔离，生产控制指令与安全相关操作保留既有控制和审批机制。\n\n试点使用可复核的样本集和明确的验收标准，记录误报、漏报、响应时间与人员反馈。数字化建议需要由现场专业人员验证，不能直接取代设备安全规程。',
    bodyEn: 'Start from an operational problem and assess the value of equipment knowledge retrieval, maintenance assistance, quality-record analysis and workflow coordination.\n\nEvaluate data quality, interfaces, connectivity and safety requirements before choosing edge or cloud deployment. Isolate integration permissions; production-control commands and safety-related actions preserve existing controls and approvals.\n\nUse reviewable samples and explicit acceptance criteria. Track false positives, missed findings, response time and staff feedback. On-site specialists validate recommendations; generated advice does not replace equipment safety procedures.',
  },
  {
    type: 'solution', slug: 'low-altitude-ecosystem', category: 'EMERGING ECOSYSTEMS', featured: true,
    title: '低空经济与分布式网络', titleEn: 'Low-altitude & distributed networks',
    summary: '探索任务协同、数据管理与资源调度，为新兴产业建立可验证的技术路径。',
    summaryEn: 'Explore mission coordination, data management and resource scheduling for emerging industries.',
    body: '面向低空经济与分布式设备协作，探索任务资料管理、设备状态汇聚、运营数据分析和资源调度辅助等技术方向。\n\n项目启动前需明确应用场景、设备能力、必要授权、责任主体与适用的运营规则。网站展示技术方向，不表示已取得飞行、运营或其他特定资质。\n\n先在受控环境验证数据链路、身份认证、故障回退与人员协同。涉及实际设备操作、飞行决策与现场安全时，专业运营人员与既有安全流程保持最终控制。',
    bodyEn: 'Explore mission-document management, device-status aggregation, operational analytics and resource-scheduling assistance for low-altitude and distributed device ecosystems.\n\nDefine the use case, device capabilities, required authorizations, accountable operators and applicable operating rules before a project begins. This page presents technology directions and does not claim flight, operating or other specific qualifications.\n\nValidate data paths, identity, fallback and human coordination in a controlled environment. Qualified operators and established safety processes retain final control of physical operations, flight decisions and field safety.',
  },
  {
    type: 'insight', slug: 'from-ai-demo-to-delivery', category: 'PERSPECTIVES', featured: true,
    title: '从 AI 演示到业务交付，中间还缺什么？', titleEn: 'What turns an AI demo into business delivery?',
    summary: '一条可验证的交付路径，需要同时回答价值、数据、质量、责任与运行五个问题。',
    summaryEn: 'A verifiable delivery path must address value, data, quality, accountability and operations.',
    body: '演示让人看见可能性，交付需要证明可用性。进入真实业务后，系统要面对不完整输入、变化的权限、多样的用户和不可预期的失败。\n\n第一步是建立业务基线：当前耗时、质量、成本与风险分别是多少？第二步是确定评估集与验收标准，覆盖常见任务、边界情况和必须拒绝的请求。第三步是设计人工接管、运行监控与问题回溯。\n\n只有将这些条件与业务目标一起写入交付范围，团队才可能判断系统是否值得扩大应用。这是一篇方法论观点文章，具体结论需要项目实测支持。',
    bodyEn: 'A demo shows possibility; delivery requires evidence of usability. Real workflows introduce incomplete inputs, changing permissions, diverse users and unexpected failures.\n\nFirst establish the operating baseline: current time, quality, cost and risk. Then define evaluation samples and acceptance criteria across normal tasks, edge cases and requests the system must refuse. Finally design human takeover, monitoring and incident traceability.\n\nPutting these conditions alongside business goals makes an expansion decision possible. This article presents a methodology; project-specific conclusions require measurement.',
  },
  {
    type: 'insight', slug: 'compute-that-fits-the-workload', category: 'ENGINEERING', featured: false,
    title: '算力规划，先回答负载问题', titleEn: 'Compute planning begins with the workload',
    summary: '从吞吐、延迟、可用性和数据边界出发，建立可比较的性能与成本基线。',
    summaryEn: 'Build comparable performance and cost baselines around throughput, latency, availability and data boundaries.',
    body: '算力选型不是孤立比较设备参数。模型、上下文长度、并发、量化策略与缓存方式都会改变资源需求。\n\n规划时应选择代表性任务，记录端到端响应时间、有效吞吐、失败率和单位任务成本。再结合部署区域、数据边界、恢复目标与供应条件比较方案。\n\n公开的基准测试可以帮助提出问题，但不能代替自身工作负载测试。容量与成本承诺应建立在双方确认的负载、测量方法和服务水平之上。',
    bodyEn: 'Compute selection is not a standalone comparison of hardware specifications. Models, context length, concurrency, quantization and caching all change resource demand.\n\nUse representative tasks to measure end-to-end latency, useful throughput, failure rate and cost per completed task. Compare options against deployment regions, data boundaries, recovery objectives and resource availability.\n\nPublic benchmarks inform questions but do not replace workload-specific testing. Capacity and cost commitments require agreed workloads, measurement methods and service levels.',
  },
  {
    type: 'insight', slug: 'governance-by-design', category: 'RESPONSIBLE AI', featured: false,
    title: '把治理放进系统设计的第一天', titleEn: 'Build governance into day one',
    summary: '从权限、来源引用、人工复核和审计记录入手，让可信成为具体的系统能力。',
    summaryEn: 'Make trust concrete through permissions, source attribution, human review and auditable records.',
    body: '治理不应是上线后的补充文档。它决定系统能读取哪些资料、调用哪些工具、执行哪些动作，以及出现问题时谁能解释和处理。\n\n在设计阶段确定数据分级、访问控制、保留期限、模型使用范围与人工审批点。对重要输出保留来源与版本，对关键操作记录主体、时间和动作，避免在日志中复制敏感内容。\n\n治理也需要验证：测试越权访问、错误引用、工具误调用和失败回退。明确知道系统何时需要停止与转交给人，是可靠交付的一部分。',
    bodyEn: 'Governance is not an after-launch document. It determines which information a system can access, which tools it can call, which actions it may take and who can explain or resolve failures.\n\nDefine data classification, access, retention, permitted model use and human approval points during design. Preserve source and version context for important outputs, and log actors, timestamps and key actions without unnecessarily duplicating sensitive content.\n\nGovernance also needs testing: unauthorized access, incorrect references, tool misuse and failure recovery. Knowing when to stop and hand control to a person is part of reliable delivery.',
  },
  {
    type: 'service', slug: 'inference-fabric', category: 'CCT INFERENCE FABRIC', featured: true,
    title: '推理基础设施与 FinOps', titleEn: 'Inference fabric & FinOps',
    summary: '统一接入异构算力与多模型，把吞吐、时延、质量、成本和服务等级放进同一套运行控制面。',
    summaryEn: 'Unify heterogeneous compute and models across throughput, latency, quality, cost and service-level controls.',
    body: 'CCT Inference Fabric 面向进入生产阶段的 AI 工作负载，规划统一推理网关、模型路由、批处理、缓存、量化、弹性调度、容量与故障隔离。它关注的是每个已完成任务的成本和质量，而不是孤立的 GPU 参数。\n\n运行控制覆盖租户与配额、调用追踪、SLA、预算钱包、成本归集、容量预测、降级与灾备。先用代表性负载建立基线，再选择公有云、私有化或混合架构。\n\n页面描述的是产品化能力方向。支持的芯片、云区域、峰值并发、可用性与价格，须在技术验收和资源合同中逐项确认。',
    bodyEn: 'CCT Inference Fabric is designed for production AI workloads, with a unified inference gateway, model routing, batching, caching, quantization, elastic scheduling, capacity controls and fault isolation. It optimizes the cost and quality of a completed task rather than comparing GPU specifications in isolation.\n\nThe operating plane covers tenants and quotas, traces, service levels, budget wallets, cost allocation, capacity forecasts, degradation and recovery. Representative workloads establish a baseline before selecting public, private or hybrid infrastructure.\n\nThis page describes a product direction. Supported accelerators, regions, peak concurrency, availability and pricing require technical acceptance and a resource contract.',
  },
  {
    type: 'service', slug: 'private-ai', category: 'CCT PRIVATE AI', featured: true,
    title: '私有 AI 与数据主权', titleEn: 'Private AI & data sovereignty',
    summary: '以数据、知识产权和部署控制为边界，设计本地、VPC、单租户与离线环境的 AI 系统。',
    summaryEn: 'Design on-premises, VPC, single-tenant and offline AI around data, IP and deployment control.',
    body: '从数据驻留、网络隔离、模型选择、密钥管理和运维责任出发，形成单租户、专有云、本地机房或受控离线环境的部署方案。\n\n能力清单包括细粒度权限、敏感数据脱敏、密钥托管、模型与数据不出域策略、异构硬件适配、审计证据、备份恢复和多云迁移。每项能力通过架构评审、渗透测试或恢复演练形成验收证据。\n\n“主权”不代表天然合规。具体数据处理活动仍需由客户的法务、安全和数据责任人确认适用要求。',
    bodyEn: 'Start from residency, network isolation, model choice, key management and operating accountability to design single-tenant, private-cloud, on-premises or controlled offline deployment.\n\nThe capability checklist covers granular access, sensitive-data handling, customer-managed keys, in-domain model and data policies, heterogeneous hardware, audit evidence, recovery and multi-cloud portability. Architecture reviews, security tests and recovery exercises provide acceptance evidence.\n\nSovereign deployment is not automatically compliant. The customer’s legal, security and data owners must confirm requirements for each processing activity.',
  },
  {
    type: 'service', slug: 'ai-control-plane', category: 'CCT AI CONTROL PLANE', featured: true,
    title: '智能体治理控制平面', titleEn: 'AI & agent control plane',
    summary: '登记每个模型、智能体、工具和责任人，在上线前评测，在运行中追踪，在高影响动作前保留人工审批。',
    summaryEn: 'Register every model, agent, tool and owner; evaluate before release, trace in production and gate consequential actions.',
    body: '控制平面建立模型与智能体登记册，记录版本、用途、数据范围、工具权限、责任人和风险等级。策略即代码把允许、拒绝、审批、预算与停机条件写入运行链路。\n\n上线门禁覆盖离线评测、红队测试、提示注入与数据泄漏测试、来源引用、拒绝行为和回归检查；运行阶段保留追踪、内容标识、事件响应与审计证据包。\n\n治理框架可参考 NIST AI RMF 等公开标准，但是否符合特定法律、行业规范或认证要求，需要独立的法务与认证评估。',
    bodyEn: 'The control plane maintains a registry of models and agents, recording version, purpose, data scope, tool permissions, accountable owner and risk tier. Policy as code brings allow, deny, approval, budget and shutdown rules into the runtime.\n\nRelease gates cover offline evaluation, red teaming, prompt-injection and data-loss tests, citation behavior, refusal and regression. Production controls add traces, content disclosure, incident response and audit evidence.\n\nPublic frameworks such as the NIST AI RMF can inform design. Compliance with a specific law, sector rule or certification requires independent legal and assurance review.',
  },
  {
    type: 'service', slug: 'green-compute', category: 'CCT GREEN COMPUTE', featured: false,
    title: '算能协同与容量治理', titleEn: 'Compute-energy coordination',
    summary: '把 GPU 利用率、队列、功耗、热风险、供电与成本联动，提前发现限制生产交付的容量瓶颈。',
    summaryEn: 'Connect utilization, queues, power, thermal risk, supply and cost to expose delivery bottlenecks early.',
    body: '算能协同关注工作负载与物理资源之间的真实约束。统一观察 GPU 利用率、排队时间、单位任务能耗、机架功率、热风险、容量余量与电力来源台账。\n\n运营策略可包括峰谷调度、冷热数据分层、容量预测、故障与热风险预警，以及成本、能耗和时延的多目标优化。PUE、碳排和可再生能源比例只有在测量边界、时间范围与凭证完整时才对外披露。\n\n实际节能与成本效果以现场基线、设备条件和试运行数据为准。',
    bodyEn: 'Compute-energy coordination addresses physical constraints behind AI workloads. It observes GPU utilization, queue time, energy per task, rack power, thermal risk, remaining capacity and electricity-source records in one operating view.\n\nOperating strategies may include time-shifting, storage tiering, capacity forecasts, failure and thermal alerts, and multi-objective optimization across cost, energy and latency. PUE, carbon and renewable claims require defined boundaries, time periods and evidence.\n\nSavings and cost outcomes depend on the measured site baseline, equipment and pilot results.',
  },
  {
    type: 'service', slug: 'physical-ai-lab', category: 'CCT PHYSICAL AI LAB', featured: false, claimScope: 'proposal',
    title: '具身智能联合实验室', titleEn: 'Physical AI joint lab',
    summary: '以数字孪生、工业视觉、边缘推理和安全围栏开展联合试点，通过阶段门决定是否进入现场规模化。',
    summaryEn: 'Run gated pilots in digital twins, industrial vision, edge inference and safety controls before field scale-up.',
    body: '具身智能目前适合以联合验证方式推进。先在仿真或数字孪生环境定义任务、失败边界与安全约束，再进入受控现场测试。\n\n试点模块包括传感器与视觉、边缘推理、任务规划、机器人接口、人工接管、操作日志和故障回退。验收关注任务成功率、安全事件、人工介入、节拍、维护成本与停机影响。\n\n该能力处于联合试点与生态共建方向，不代表已经拥有机器人量产能力、现场资质或规模化收入。',
    bodyEn: 'Physical AI is advanced through joint validation. Define tasks, failure boundaries and safety constraints in simulation or a digital twin before controlled field testing.\n\nPilot modules cover sensors and vision, edge inference, planning, robot interfaces, human takeover, operating logs and fail-safe behavior. Acceptance measures task success, safety events, intervention, cycle time, maintenance cost and downtime impact.\n\nThis is a joint-pilot and ecosystem direction. It does not claim robot manufacturing capacity, field qualification or scaled revenue.',
  },
  {
    type: 'solution', slug: 'customer-operations-agents', category: 'CUSTOMER OPERATIONS', featured: true,
    title: '客户运营智能体', titleEn: 'Customer operations agents',
    summary: '把多渠道消息、知识、线索、工单与 CRM 回写串成可追踪的执行闭环。',
    summaryEn: 'Connect conversations, knowledge, leads, tickets and CRM updates into a traceable execution loop.',
    body: '输入包括授权渠道消息、客户上下文、产品知识和服务规则。智能体识别意图，检索依据，生成或执行下一步，并在外部写入、承诺、退款和敏感场景前触发人工审批。\n\n执行证据包含所用来源、工具调用、审批人、状态回写与最终结果。异常、超时和低置信度任务进入人工队列，避免静默失败。\n\n试点 KPI 包括一次解决率、准确率、人工复核率、响应时间、转人工原因、单位处理成本与客户反馈。基线和目标由项目双方共同确认。',
    bodyEn: 'Inputs include authorized conversations, customer context, product knowledge and service rules. Agents classify intent, retrieve evidence, prepare or execute the next step, and request human approval before external writes, commitments, refunds or sensitive actions.\n\nExecution evidence records sources, tool calls, approvals, status updates and outcomes. Exceptions, timeouts and low-confidence tasks enter a human queue rather than failing silently.\n\nPilot metrics include first-contact resolution, correctness, review rate, response time, handoff reasons, unit cost and customer feedback. The project parties agree the baseline and targets.',
  },
  {
    type: 'solution', slug: 'geo-growth-intelligence', category: 'GEO & GROWTH', featured: true,
    title: 'GEO 增长智能系统', titleEn: 'GEO growth intelligence',
    summary: '持续测量品牌在生成式搜索中的可见度、引用与竞品差距，把诊断、内容执行和复测连成闭环。',
    summaryEn: 'Measure visibility, citations and competitive gaps in generative search, then connect diagnosis, action and remeasurement.',
    body: '系统按预先定义的问题集和目标受众运行测量，记录不同模型或入口的品牌出现、来源引用、答案位置和竞品表现。诊断将问题映射到内容缺口、权威信源、技术可抓取性与品牌实体一致性。\n\n执行工作台形成选题、证据、审核、发布准备与复测任务。所有内容保留来源和人工编辑，避免以批量生成替代真实专业知识。\n\n结果以可重复的问题集、时间窗和来源证据呈现。生成式答案会随模型、地区与时间变化，因此不承诺固定排名或永久引用。',
    bodyEn: 'The system runs a defined question set for target audiences and records brand presence, citations, answer position and competitor performance across models or surfaces. Diagnosis maps gaps to content, authoritative sources, crawlability and brand-entity consistency.\n\nThe workbench creates topics, evidence, review, publication-ready work and remeasurement tasks. Sources and human editing stay attached to content so volume does not replace expertise.\n\nResults use repeatable questions, time windows and source evidence. Generative answers vary by model, region and time; fixed rankings or permanent citations are not promised.',
  },
  {
    type: 'solution', slug: 'ai-commerce-operations', category: 'AI COMMERCE', featured: false,
    title: 'AI 电商与内容运营', titleEn: 'AI commerce & content operations',
    summary: '连接商品知识、内容生产、营销协同、客服与订单，让每次自动化都有审核、预算和结果证据。',
    summaryEn: 'Connect product knowledge, content, campaigns, service and orders with review, budget and outcome evidence.',
    body: '以商品主数据和品牌规则为基础，编排研究、文案、素材、渠道适配、客服辅助与订单协同。不同模型按任务质量、成本和时延路由，生成内容在发布前经过版权、事实、品牌与合规审核。\n\n涉及价格、库存、订单、退款和用户权益的动作，通过业务系统 API 和权限策略执行；关键变更保留人工批准与回滚路径。\n\n试点衡量内容一次通过率、制作周期、人工返工、转化链路、服务质量与单位成本。任何增长比例都需来自明确的对照基线。',
    bodyEn: 'Use governed product data and brand rules to orchestrate research, copy, media, channel adaptation, service assistance and order coordination. Route models by quality, cost and latency, and review copyright, facts, brand and compliance before publishing.\n\nPrice, inventory, order, refund and customer-rights actions use governed business APIs. Consequential changes retain human approval and rollback.\n\nPilots measure first-pass acceptance, production cycle, rework, conversion flow, service quality and unit cost. Any growth percentage requires a defined comparison baseline.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-infrastructure-2026', category: 'MARKET SIGNAL · INFRASTRUCTURE', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'NVIDIA Investor Relations', sourceUrl: 'https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-Second-Quarter-Fiscal-2027/', sourceDate: '2026-08-26',
    title: 'AI 基础设施：收入与毛利证据最强的商业主航道', titleEn: 'AI infrastructure: the strongest current revenue signal',
    summary: 'NVIDIA 披露 FY2027 Q2 数据中心收入 890 亿美元，同比增长 117%；该数字是全球市场信号，不是 CCT 业绩。',
    summaryEn: 'NVIDIA reported $89B in Q2 FY2027 data-center revenue, up 117% year over year. This is a market signal, not CCT performance.',
    body: 'NVIDIA 于 2026 年 8 月 26 日披露，FY2027 第二季度数据中心收入为 890 亿美元，同比增长 117%，公司 GAAP 毛利率为 75%。\n\n这说明推理算力、网络、系统软件和数据中心交付仍具强商业化强度。对 CCT 的产品启示是：价值不能停留在转售 GPU，而应覆盖资源编排、推理效率、可观测、FinOps、SLA 与持续运维。\n\n来源数字属于 NVIDIA 官方披露，不代表 CCT 的收入、客户、算力规模或盈利能力。',
    bodyEn: 'On 26 August 2026, NVIDIA reported Q2 FY2027 data-center revenue of $89 billion, up 117% year over year, and a company GAAP gross margin of 75%.\n\nThe signal supports continued demand for inference compute, networking, systems software and data-center delivery. For CCT, the product implication is to extend beyond GPU resale into orchestration, inference efficiency, observability, FinOps, service levels and managed operations.\n\nThese figures are NVIDIA disclosures. They are not CCT revenue, customer, capacity or margin claims.',
  },
  {
    type: 'insight', slug: 'market-signal-enterprise-agents-2026', category: 'MARKET SIGNAL · AGENTS', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Salesforce Investor Relations', sourceUrl: 'https://investor.salesforce.com/news/news-details/2026/Salesforce-Delivers-Record-Second-Quarter-Fiscal-2027-Results/default.aspx', sourceDate: '2026-08-26',
    title: '企业智能体：从对话入口转向可计量的业务动作', titleEn: 'Enterprise agents: from chat to metered work',
    summary: 'Salesforce 披露 Agentforce ARR 超过 15 亿美元、同比增长 240%，显示生产级智能体正形成清晰付费需求。',
    summaryEn: 'Salesforce reported Agentforce ARR above $1.5B, up 240%, indicating paid demand for production agents.',
    body: 'Salesforce 于 2026 年 8 月 26 日披露，Agentforce 年度经常性收入超过 15 亿美元，同比增长 240%；Agentforce 与 Data 360 合计 ARR 接近 39 亿美元。\n\n商业信号指向“席位加动作/消耗”的混合计费，以及企业数据、工具、治理和结果度量的一体化。CCT AgentOS 因此以任务完成、人工复核、延迟和单位成本为核心指标。\n\n来源口径由 Salesforce 定义，且产品统计范围可能变化；该数字不代表 CCT 订单或收入。',
    bodyEn: 'On 26 August 2026, Salesforce reported Agentforce ARR above $1.5 billion, up 240% year over year, and combined Agentforce and Data 360 ARR near $3.9 billion.\n\nThe signal points to hybrid seat-plus-action or consumption pricing, together with enterprise data, tools, governance and outcome measurement. CCT AgentOS therefore focuses on task completion, human review, latency and unit cost.\n\nSalesforce defines these metrics and may change scope. They do not represent CCT orders or revenue.',
  },
  {
    type: 'insight', slug: 'market-signal-industry-ai-2026', category: 'MARKET SIGNAL · INDUSTRY AI', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'Palantir Q2 2026 Form 10-Q', sourceUrl: 'https://investors.palantir.com/files/2026%20Q2%20PLTR%2010-Q.pdf', sourceDate: '2026-08-03',
    title: '行业 AI：业务语义、数据与工作流形成高价值合同', titleEn: 'Industry AI: semantics, data and workflows drive value',
    summary: 'Palantir 披露 2026 Q2 商业收入同比增长 110%、毛利率 85%，体现行业操作平台的商业质量。',
    summaryEn: 'Palantir reported Q2 2026 commercial revenue growth of 110% and an 85% gross margin, a strong industry-platform signal.',
    body: 'Palantir 在 2026 年第二季度 10-Q 中披露，季度收入 19.35 亿美元，同比增长 93%；商业收入 9.45 亿美元，同比增长 110%；毛利率 85%。\n\n市场信号表明，连接业务语义、受治理数据、工作流与执行型智能体的平台，可能比通用聊天入口更容易形成高价值项目。CCT 行业方案因此采用“输入、决策、动作、证据、KPI”的闭环结构。\n\nPalantir 的财务表现不能直接推导 CCT 的价格、毛利或增长，CCT 项目仍须通过自身合同与验收数据证明。',
    bodyEn: 'Palantir reported Q2 2026 revenue of $1.935 billion, up 93%, commercial revenue of $945 million, up 110%, and an 85% gross margin.\n\nThe signal suggests platforms connecting business semantics, governed data, workflows and executing agents can support high-value projects more effectively than a generic chat interface. CCT industry solutions therefore use an input, decision, action, evidence and KPI loop.\n\nPalantir performance does not establish CCT pricing, margin or growth. CCT projects require their own contracts and acceptance evidence.',
  },
  {
    type: 'insight', slug: 'market-signal-energy-ai-2030', category: 'MARKET SIGNAL · ENERGY', featured: true, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'International Energy Agency · Energy and AI', sourceUrl: 'https://www.iea.org/reports/energy-and-ai/executive-summary', sourceDate: '2025-04-10',
    title: '算能协同：AI 增长把供电与效率推到交付前线', titleEn: 'Compute and energy: power becomes a delivery constraint',
    summary: 'IEA 基准情景预计全球数据中心用电到 2030 年增至约 945 TWh，较当前水平翻倍以上。',
    summaryEn: 'The IEA base case projects global data-center electricity use to exceed double today’s level, reaching about 945 TWh by 2030.',
    body: '国际能源署《Energy and AI》基准情景预计，全球数据中心用电到 2030 年增至约 945 TWh，较当前水平翻倍以上；AI 是增长的最重要驱动因素。\n\n这使供电、并网、散热、容量和能源成本成为 AI 系统交付的一部分。CCT Green Compute 将利用率、队列、功耗、热风险、容量与成本纳入同一运行视图。\n\n该数字是 IEA 情景预测，存在硬件效率、部署速度和能源系统等不确定性，不是 CCT 能耗、节能或减碳成绩。',
    bodyEn: 'The International Energy Agency’s Energy and AI base case projects global data-center electricity consumption at about 945 TWh in 2030, more than double today’s level, with AI the most important driver.\n\nPower access, grids, cooling, capacity and energy cost therefore become part of AI delivery. CCT Green Compute brings utilization, queues, power, thermal risk, capacity and cost into one operating view.\n\nThe figure is an IEA scenario with uncertainty in efficiency, deployment and energy systems. It is not a CCT energy, savings or carbon result.',
  },
  {
    type: 'insight', slug: 'market-signal-ai-governance-2026', category: 'MARKET SIGNAL · GOVERNANCE', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'European Commission · AI Act enforcement', sourceUrl: 'https://digital-strategy.ec.europa.eu/en/news/commission-starts-enforcing-ai-act-rules-and-new-transparency-requirements-2-august', sourceDate: '2026-07-31',
    title: 'AI 治理：透明、标识与审计从建议进入执行', titleEn: 'AI governance: transparency and audit enter enforcement',
    summary: '欧盟委员会确认自 2026 年 8 月 2 日开始执行相关 AI Act 权力与透明要求。',
    summaryEn: 'The European Commission confirmed enforcement powers and relevant AI Act transparency rules from 2 August 2026.',
    body: '欧盟委员会于 2026 年 7 月 31 日说明，从 8 月 2 日起开始执行相关 AI Act 权力与透明要求：特定交互式 AI 需要告知用户其 AI 身份，生成或篡改内容适用标识与机器可读要求。\n\n这使智能体登记、责任人、运行追踪、内容标识、评测门禁、人工审批和事件响应成为跨境系统的设计输入。\n\n法规适用取决于角色、市场、用途和系统风险。官网信息不构成法律意见，项目应由合格法务确认适用条款和时间。',
    bodyEn: 'On 31 July 2026, the European Commission stated that relevant AI Act enforcement powers and transparency requirements would apply from 2 August. Certain interactive AI must disclose that users are dealing with AI, while generated or manipulated content is subject to disclosure and machine-readable marking rules.\n\nAgent registries, ownership, traces, content disclosure, evaluation gates, human approval and incident response therefore become design inputs for cross-border systems.\n\nApplicability depends on role, market, use and risk. This site is not legal advice; qualified counsel should confirm project obligations and dates.',
  },
  {
    type: 'insight', slug: 'market-signal-physical-ai-2025', category: 'MARKET SIGNAL · PHYSICAL AI', featured: false, claimScope: 'market', evidenceLevel: 'official', sourceLabel: 'International Federation of Robotics · World Robotics 2025', sourceUrl: 'https://ifr.org/img/worldrobotics/Executive_Summary_WR_2025_Industrial_Robots.pdf', sourceDate: '2025-09-25',
    title: '具身智能：机器人存量巨大，但 AI 盈利证据仍需分开看', titleEn: 'Physical AI: large robot adoption, distinct AI economics',
    summary: 'IFR 统计 2024 年全球新增工业机器人约 54.2 万台、运营存量约 466 万台；这不等于具身大模型收入。',
    summaryEn: 'IFR counted about 542,000 industrial robot installations and 4.66M operational units in 2024; this is not embodied-model revenue.',
    body: '国际机器人联合会《World Robotics 2025》统计，2024 年全球新增工业机器人约 54.2 万台，运营存量约 466 万台；中国占全球新增安装的 54%。\n\n机器人部署基础为视觉、仿真、边缘推理与智能任务规划提供了场景，但工业机器人安装量不能等同于具身大模型收入、利润或自动化收益。\n\n因此 CCT 将 Physical AI 定位为联合实验室与阶段化试点，在仿真、安全围栏和现场验收后再决定扩展。',
    bodyEn: 'The International Federation of Robotics counted roughly 542,000 new industrial robot installations and about 4.66 million operational units in 2024; China accounted for 54% of new installations.\n\nThis installed base creates opportunities for vision, simulation, edge inference and intelligent planning, but robot installations are not embodied-model revenue, profit or automation returns.\n\nCCT therefore positions Physical AI as a joint lab with gated pilots, requiring simulation, safety controls and field acceptance before scale-up.',
  },
];
